repo = "github.com/mjs/directnic_ddns"
rule = "codelingo/go/default-in-type-switch"
sha = "6082c54efb4389e02259894f5f83534438609803"

[[issues]]
  fileline = 91
  filepath = "vendor/github.com/pelletier/go-toml/tomltree_write.go"
  fixed = false
  ignored = "handled by fallthrough"

[[issues]]
  fileline = 319
  filepath = "vendor/github.com/pelletier/go-toml/tomltree_write.go"
  fixed = false
  ignored = "in vendor"

[[issues]]
  fileline = 203
  filepath = "vendor/github.com/pelletier/go-toml/toml.go"
  fixed = false
  ignored = "in vendor"

[[issues]]
  fileline = 266
  filepath = "vendor/github.com/pelletier/go-toml/toml.go"
  fixed = false
  ignored = "in vendor"

[[issues]]
  fileline = 220
  filepath = "vendor/github.com/pelletier/go-toml/tomltree_write.go"
  fixed = false
  ignored = "in vendor"
