repo = "github.com/kphf1995cm/MIT-6.824"
rule = "codelingo/go/shadowed-variable"
sha = "6984407071aac4c5f0f8d8b48975d1ab742cef4e"

[[issues]]
  filepath = "src/labrpc/test_test.go"
  fileline = 225

[[issues]]
  filepath = "src/labrpc/test_test.go"
  fileline = 339

[[issues]]
  filepath = "src/mapreduce/master_splitmerge.go"
  fileline = 20

[[issues]]
  filepath = "src/raft/test_test.go"
  fileline = 803

[[issues]]
  filepath = "src/raft/config.go"
  fileline = 388
