repo = "github.com/spf13/cobra"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "95f2f73ed97e57387762620175ccdc277a8597a0"

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 55
  comment = "The variable stdin should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 55
  comment = "The variable byte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 56
  comment = "The variable stdin should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 55
  comment = "The variable s should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 55
  comment = "The variable Write should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "bash_completions_test.go"
  fileline = 56
  comment = "The variable Close should be passed in as arguments to go-routines to avoid race conditions."
