repo = "github.com/rakyll/hey"
rule = "codelingo/go/unchecked-type-assertion"
sha = "f3676ef133bcbda356147da8c0ded4d36d1d28f5"

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 1344
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/frame.go"
  fileline = 1546
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 1312
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 946
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 1155
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 947
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/hpack/hpack.go"
  fileline = 485
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/gotrack.go"
  fileline = 52
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/write.go"
  fileline = 51
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/hpack/huffman.go"
  fileline = 22
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/hpack/huffman.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/write.go"
  fileline = 335
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 2113
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/frame.go"
  fileline = 1576
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 835
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/http2.go"
  fileline = 281
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 2053
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/text/unicode/bidi/bracket.go"
  fileline = 160
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 2474
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/frame.go"
  fileline = 231
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/transport.go"
  fileline = 1645
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
