repo = "github.com/friendlydan/dash-demo"
rule = "missing-close-file"
sha = "6bad7b7ab520ce73c7868632d08994b8aec3260e"

[[issues]]
  fileline = 38
  filepath = "main.go"
  fixed = true
  ignored = ""

[[issues]]
  fileline = 15
  filepath = "main.go"
  fixed = false
  ignored = "test"

[[issues]]
  fileline = 31
  filepath = "main.go"
  fixed = true
  ignored = ""

[[issues]]
  fileline = 21
  filepath = "main.go"
  fixed = false
  ignored = "test"
