repo = "github.com/containous/traefik"
rule = "codelingo/go/insecure-http-connection"
sha = "16c48071621ac2f38bd02d55854574f384c913f0"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 87
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 849
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 143
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 842
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 780
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 159
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 93
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 151
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 912
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 229
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 773
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 237
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 350
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 1093
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 423
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 534
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 40
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 654
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 673
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 488
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 288
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 578
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 630
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 558
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 386
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 458
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 314
  filepath = "integration/https_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 196
  filepath = "integration/tcp_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 54
  filepath = "integration/tcp_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 453
  filepath = "integration/acme_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 466
  filepath = "integration/acme_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 63
  filepath = "integration/tls_client_headers_test.go"
  fixed = false
  ignored = "in test"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 70
  filepath = "pkg/server/service/roundtripper.go"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 575
  filepath = "pkg/server/service/proxy_websocket_test.go"

[[issues]]
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
  fileline = 594
  filepath = "pkg/server/service/proxy_websocket_test.go"
