repo = "github.com/github/gh-ost"
rule = "codelingo/go/insecure-http-connection"
sha = "4dab06e92b20954b46301e3b176d3a873615e3af"

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 294
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 1302
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 666
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 869
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/dsn.go"
  fileline = 126
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 666
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 1302
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 294
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/auth_test.go"
  fileline = 869
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/dsn.go"
  fileline = 126
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "go/mysql/connection_test.go"
  fileline = 35
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
