repo = "github.com/github/gh-ost"
rule = "codelingo/go/default-in-type-switch"
sha = "4dab06e92b20954b46301e3b176d3a873615e3af"

[[issues]]
  filepath = "vendor/github.com/jmoiron/sqlx/sqlx.go"
  fileline = 433
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/agent/client.go"
  fileline = 354
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/main.go"
  fileline = 48
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/main.go"
  fileline = 48
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go"
  fileline = 719
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/keys_test.go"
  fileline = 25
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/schema/schema.go"
  fileline = 327
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/go-sql-driver/mysql/utils.go"
  fileline = 137
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/agent/client.go"
  fileline = 319
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/BurntSushi/toml/encode.go"
  fileline = 113
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/BurntSushi/toml/encode.go"
  fileline = 157
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/BurntSushi/toml/encode.go"
  fileline = 158
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/text/encoding/internal/identifier/gen.go"
  fileline = 90
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/satori/go.uuid/sql.go"
  fileline = 38
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/keys.go"
  fileline = 708
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/BurntSushi/toml/encode.go"
  fileline = 113
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/canal/rows.go"
  fileline = 54
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/go-sql-driver/mysql/utils.go"
  fileline = 137
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/github.com/siddontang/go-mysql/vendor/github.com/pingcap/check/printer.go"
  fileline = 126
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/ssh/keys.go"
  fileline = 697
  comment = "Always include a default case when using a type switch."
