repo = "github.com/go-sql-driver/mysql"
rule = "codelingo/go/shadowed-variable"
sha = "681ffa848bae8d0d7b1a452963c0705b132308f7"

[[issues]]
  filepath = "driver_test.go"
  fileline = 3106
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "statement_test.go"
  fileline = 109
  comment = "Variable output shadows a variable of the same name declared in an outer scope."
