repo = "test/example"
rule = "one"

[[issues]]
  filepath = "example.go"
  fileline = 5
  fixed = false
  ignored = ""

[[issues]]
  filepath = "example2.go"
  fileline = 5
  fixed = false
  ignored = ""
