repo = "github.com/buger/goreplay"
rule = "codelingo/go/shadowed-variable"
sha = "ffc1a09ca1e465dc1b67efc151dab2771e1086c7"

[[issues]]
  filepath = "vendor/github.com/google/gopacket/layers/gtp.go"
  fileline = 132
  comment = "Variable data shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/pierrec/lz4/block.go"
  fileline = 377
  comment = "Variable lLen shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/pierrec/lz4/block.go"
  fileline = 201
  comment = "Variable lLen shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "proto/proto.go"
  fileline = 351
  comment = "Variable newPath shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/google/gopacket/layers/ip6.go"
  fileline = 245
  comment = "Variable pEnd shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/google/gopacket/layers/ip6.go"
  fileline = 250
  comment = "Variable pEnd shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/pierrec/xxHash/xxHash32/xxHash32.go"
  fileline = 163
  comment = "Variable p shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/google/gopacket/packet.go"
  fileline = 660
  comment = "Variable p shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "output_file_settings.go"
  fileline = 21
  comment = "Variable size shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/pierrec/lz4/writer.go"
  fileline = 296
  comment = "Variable m shadows a variable of the same name declared in an outer scope."
