repo = "github.com/bilibili/kratos"
rule = "codelingo/go/break-select-in-for"
sha = "8de8758d3d5f40ea047de945c5969fab59a2acda"

[[issues]]
  filepath = "pkg/sync/pipeline/pipeline.go"
  fileline = 184
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
