repo = "github.com/gadelkareem/cachita"
rule = "codelingo/go/unchecked-type-assertion"
sha = "27c05434ad48d5cbb92e0af613152ed5ac17dbe5"

[[issues]]
  filepath = "cache_test.go"
  fileline = 173

[[issues]]
  filepath = "cache.go"
  fileline = 108

[[issues]]
  filepath = "cache_test.go"
  fileline = 174
