repo = "github.com/turkogluc/xssGo"
rule = "shadowed-variable"
sha = "133e0f4913f79c4c75045c2918375938212e40b4"

[[issues]]
  fileline = 402
  filepath = "source/selenium.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 411
  filepath = "source/selenium.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 249
  filepath = "source/selenium.go"
  fixed = false
  ignored = "fp"
