repo = "github.com/micro/go-micro"
rule = "codelingo/go/unchecked-type-assertion"
sha = "03031a694da1b256d0d7f2afb1a2926954c63c85"

[[issues]]
  filepath = "client/grpc/options.go"
  fileline = 68
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/bytes/bytes.go"
  fileline = 32
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server/grpc/grpc.go"
  fileline = 466
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 152
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 161
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "util/ring/buffer_test.go"
  fileline = 15
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/bytes/marshaler.go"
  fileline = 27
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 140
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "config/source/cli/cli_test.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "api/server/acme/certmagic/certmagic.go"
  fileline = 32
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server/grpc/grpc.go"
  fileline = 372
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/text/text.go"
  fileline = 32
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 170
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 176
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 158
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server/grpc/grpc.go"
  fileline = 388
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "client/grpc/grpc.go"
  fileline = 50
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "agent/input/telegram/conn.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "agent/input/slack/conn.go"
  fileline = 84
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/bytes/bytes.go"
  fileline = 46
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "agent/input/telegram/conn.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "config/source/env/env_test.go"
  fileline = 36
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 164
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "util/addr/addr.go"
  fileline = 87
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "debug/trace/memory/memory.go"
  fileline = 30
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/bytes/marshaler.go"
  fileline = 15
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "config/source/flag/flag_test.go"
  fileline = 62
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 143
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "config/source/flag/flag_test.go"
  fileline = 34
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "codec/text/text.go"
  fileline = 48
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "util/ring/buffer_test.go"
  fileline = 30
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "client/grpc/codec.go"
  fileline = 72
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 155
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "util/ring/buffer_test.go"
  fileline = 47
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 149
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "broker/memory/memory.go"
  fileline = 187
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server/rpc_router.go"
  fileline = 578
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "util/addr/addr.go"
  fileline = 143
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "client/grpc/grpc.go"
  fileline = 354
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 173
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 146
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "store/etcd/config.go"
  fileline = 167
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
