repo = "github.com/gadelkareem/awsgo"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "8f0a586ce8206840c11d27b56a938ac9ef92622e"

[[issues]]
  filepath = "AwsService.go"
  fileline = 61
