repo = "github.com/iawia002/annie"
rule = "codelingo/go/shadowed-variable"
sha = "c24fbc04b8260cc5923af12be9baf30d35735325"

[[issues]]
  filepath = "extractors/bilibili/bilibili.go"
  fileline = 301
  comment = "Variable jsonString shadows a variable of the same name declared in an outer scope."
