repo = "github.com/labstack/echo"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "fc4b1c0a830f194bf6334d2b3e61d92cccebb2be"

[[issues]]
  filepath = "echo_test.go"
  fileline = 423
  comment = "The variable StartTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 425
  comment = "The variable ErrServerClosed should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 423
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 425
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 426
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 426
  comment = "The variable assert should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 426
  comment = "The variable NoError should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 426
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 588
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 588
  comment = "The variable Start should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 588
  comment = "The variable errCh should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable require should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable expectedErr should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable test should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable Error should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 487
  comment = "The variable EqualError should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 486
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable test should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable cert should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 488
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 486
  comment = "The variable expectedErr should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 486
  comment = "The variable test should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 488
  comment = "The variable ErrServerClosed should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable StartTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable key should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable test should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 485
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 489
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 489
  comment = "The variable require should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 489
  comment = "The variable NoError should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 489
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 504
  comment = "The variable StartAutoTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 504
  comment = "The variable errChan should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 504
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 568
  comment = "The variable errCh should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 568
  comment = "The variable Start should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 568
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable NoError should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable assert should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable h2s should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 522
  comment = "The variable StartH2CServer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 415
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 415
  comment = "The variable Start should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 415
  comment = "The variable assert should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 415
  comment = "The variable NoError should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "echo_test.go"
  fileline = 415
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."
