repo = "github.com/cyfdecyf/cow"
rule = "codelingo/go/default-in-type-switch"
sha = "41c0fb157c8b939b724ae0d58dad3a1b7cd2e811"

[[issues]]
  filepath = "parent_proxy.go"
  fileline = 70
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "conn_pool.go"
  fileline = 94
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "proxy.go"
  fileline = 1240
  comment = "Always include a default case when using a type switch."
