repo = "github.com/julienschmidt/httprouter"
rule = "codelingo/go/shadowed-variable"
sha = "8c9f31f047a304abedb5614d4a18a843cd5f4a40"

[[issues]]
  filepath = "router_test.go"
  fileline = 434
  comment = "Variable w shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "router_test.go"
  fileline = 433
  comment = "Variable r shadows a variable of the same name declared in an outer scope."
