repo = "github.com/drone/drone"
rule = "codelingo/go/ticker-in-for-select"
sha = "296471d489c197881745cedb703e8c0cc23e140f"

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 75
  filepath = "handler/api/events/global.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 78
  filepath = "handler/api/events/global.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 211
  filepath = "scheduler/queue/queue.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 66
  filepath = "scheduler/queue/canceller.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 94
  filepath = "handler/api/events/build.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 97
  filepath = "handler/api/events/build.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 112
  filepath = "handler/api/events/logs.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 114
  filepath = "handler/api/events/logs.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 72
  filepath = "metric/sink/datadog.go"
  fixed = false
  ignored = "deterministic"
