repo = "github.com/tobyhede/go-underscore"
rule = "unsafe-go-routine-variables"
sha = "ea55fc9569918f099b1dfa785088434e5c53544d"

[[issues]]
  filepath = "each.go"
  fileline = 143

[[issues]]
  filepath = "each.go"
  fileline = 144

[[issues]]
  filepath = "each.go"
  fileline = 144

[[issues]]
  filepath = "each.go"
  fileline = 143

[[issues]]
  filepath = "each.go"
  fileline = 122

[[issues]]
  filepath = "each.go"
  fileline = 121

[[issues]]
  filepath = "each.go"
  fileline = 122

[[issues]]
  filepath = "each_test.go"
  fileline = 110

[[issues]]
  filepath = "each_test.go"
  fileline = 111

[[issues]]
  filepath = "each_test.go"
  fileline = 110

[[issues]]
  filepath = "each_test.go"
  fileline = 110

[[issues]]
  filepath = "each_test.go"
  fileline = 111

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each.go"
  fileline = 107

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each.go"
  fileline = 107

[[issues]]
  filepath = "each.go"
  fileline = 106

[[issues]]
  filepath = "each_test.go"
  fileline = 133

[[issues]]
  filepath = "each_test.go"
  fileline = 133

[[issues]]
  filepath = "each_test.go"
  fileline = 134

[[issues]]
  filepath = "each_test.go"
  fileline = 133

[[issues]]
  filepath = "each_test.go"
  fileline = 134

[[issues]]
  filepath = "each_test.go"
  fileline = 172

[[issues]]
  filepath = "each_test.go"
  fileline = 171

[[issues]]
  filepath = "each_test.go"
  fileline = 171

[[issues]]
  filepath = "each_test.go"
  fileline = 171

[[issues]]
  filepath = "each_test.go"
  fileline = 172
