repo = "github.com/helm/helm"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "ec1d1a3d3eb672232f896f9d3b3d0797e4f519e3"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 33
  filepath = "pkg/chartutil/expand_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 51
  filepath = "pkg/chartutil/expand_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 103
  filepath = "pkg/chartutil/expand_test.go"
  fixed = true
  ignored = ""
