repo = "github.com/BeFunes/go-test"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "f0b6715757838d21fe9a88b7e8103531e15c23cb"

[[issues]]
  filepath = "_examples/main.go"
  fileline = 89

[[issues]]
  filepath = "_examples/main.go"
  fileline = 89

[[issues]]
  filepath = "_examples/main.go"
  fileline = 89

[[issues]]
  filepath = "_examples/main.go"
  fileline = 89

[[issues]]
  filepath = "_examples/main.go"
  fileline = 94

[[issues]]
  filepath = "_examples/main.go"
  fileline = 94

[[issues]]
  filepath = "_examples/main.go"
  fileline = 94

[[issues]]
  filepath = "_examples/main.go"
  fileline = 65

[[issues]]
  filepath = "_examples/main.go"
  fileline = 77

[[issues]]
  filepath = "_examples/main.go"
  fileline = 75

[[issues]]
  filepath = "_examples/main.go"
  fileline = 65

[[issues]]
  filepath = "_examples/main.go"
  fileline = 76

[[issues]]
  filepath = "_examples/main.go"
  fileline = 76

[[issues]]
  filepath = "_examples/main.go"
  fileline = 74

[[issues]]
  filepath = "_examples/main.go"
  fileline = 82

[[issues]]
  filepath = "_examples/main.go"
  fileline = 77

[[issues]]
  filepath = "_examples/main.go"
  fileline = 68

[[issues]]
  filepath = "_examples/main.go"
  fileline = 68

[[issues]]
  filepath = "_examples/main.go"
  fileline = 82

[[issues]]
  filepath = "_examples/main.go"
  fileline = 82

[[issues]]
  filepath = "_examples/main.go"
  fileline = 76

[[issues]]
  filepath = "_examples/main.go"
  fileline = 86

[[issues]]
  filepath = "_examples/main.go"
  fileline = 70

[[issues]]
  filepath = "_examples/main.go"
  fileline = 77

[[issues]]
  filepath = "_examples/main.go"
  fileline = 82

[[issues]]
  filepath = "_examples/main.go"
  fileline = 88

[[issues]]
  filepath = "_examples/main.go"
  fileline = 71

[[issues]]
  filepath = "_examples/main.go"
  fileline = 83

[[issues]]
  filepath = "_examples/main.go"
  fileline = 69

[[issues]]
  filepath = "_examples/main.go"
  fileline = 78

[[issues]]
  filepath = "_examples/main.go"
  fileline = 86

[[issues]]
  filepath = "_examples/main.go"
  fileline = 74

[[issues]]
  filepath = "_examples/main.go"
  fileline = 77

[[issues]]
  filepath = "_examples/main.go"
  fileline = 84

[[issues]]
  filepath = "_examples/main.go"
  fileline = 84

[[issues]]
  filepath = "_examples/main.go"
  fileline = 84

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 97

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 93

[[issues]]
  filepath = "_examples/main.go"
  fileline = 92

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 88

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 89

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 88

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 89

[[issues]]
  filepath = "elasticsearch_integration_test.go"
  fileline = 90

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 55

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 56

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 55

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 56

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 55

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 53

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 57

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 53

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 58

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 58

[[issues]]
  filepath = "estransport/logger_internal_test.go"
  fileline = 58

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 120

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 120

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 120

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 119

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 119

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 117

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 119

[[issues]]
  filepath = "_examples/xkcdsearch/cmd/xkcd/commands/index.go"
  fileline = 117

[[issues]]
  filepath = "_examples/customization.go"
  fileline = 73

[[issues]]
  filepath = "_examples/customization.go"
  fileline = 74

[[issues]]
  filepath = "_examples/customization.go"
  fileline = 74

[[issues]]
  filepath = "_examples/customization.go"
  fileline = 73
