repo = "github.com/revel/revel"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "a3d7a7c23ca885cc5036d3641ede49ce4a14ee2e"

[[issues]]
  filepath = "controller.go"
  fileline = 302
  comment = "Close the file when you are done"

[[issues]]
  filepath = "fakeapp_test.go"
  fileline = 61
  comment = "Close the file when you are done"
