repo = "github.com/go-kit/kit"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "ad60314e5159aad7c4a801aa1d56862b82084066"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 75
  filepath = "cmd/kitgen/main.go"
  fixed = false
  ignored = "file leaves func"
