repo = "rfjakob/gocryptfs"
rule = "error-reassign"

[[issues]]
  filepath = "internal/configfile/config_file.go"
  fileline = 55
  fixed = false
  ignored = ""

[[issues]]
  filepath = "main.go"
  fileline = 38
  fixed = false
  ignored = ""

[[issues]]
  filepath = "internal/fusefrontend/xattr_linux.go"
  fileline = 32
  fixed = false
  ignored = ""

[[issues]]
  filepath = "tests/defaults/ctlsock_test.go"
  fileline = 59
  fixed = false
  ignored = ""
