repo = "github.com/sundy-li/html2article"
rule = "error-reassign"
sha = "09ac198090c224161026f4a4b7bb4ddce402cea6"

[[issues]]
  Name = "error-reassign"
  Comment = "Error was not checked before reassignment"
  filepath = ""
  fileline = 0
  Snippet = "\t}\n\t//@see : https://github.com/golang/net/blob/master/html/charset/charset.go\n\treader, err := charset.NewReader(resp.Body, strings.ToLower(resp.Header.Get(\"Content-Type\")))\n\tdefer resp.Body.Close()\n\tbs, err := ioutil.ReadAll(reader)"
