repo = "github.com/iikira/BaiduPCS-Go"
rule = "codelingo/go/shadowed-variable"
sha = "52394a677126a284baea7199271838037a79342f"

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/lib.go"
  fileline = 519
  comment = "Variable index shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_dynamic.go"
  fileline = 47
  comment = "Variable obj shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_marshal.go"
  fileline = 2713
  comment = "Variable siz shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_marshal.go"
  fileline = 2714
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_marshal.go"
  fileline = 2740
  comment = "Variable siz shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_map.go"
  fileline = 101
  comment = "Variable encoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_map.go"
  fileline = 189
  comment = "Variable elem shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_map.go"
  fileline = 182
  comment = "Variable key shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_map.go"
  fileline = 47
  comment = "Variable decoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/russross/blackfriday/smartypants.go"
  fileline = 126
  comment = "Variable nextChar shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_float.go"
  fileline = 250
  comment = "Variable ind shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_float.go"
  fileline = 274
  comment = "Variable ind shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_float.go"
  fileline = 113
  comment = "Variable ind shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_float.go"
  fileline = 137
  comment = "Variable ind shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 314
  comment = "Variable encoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 304
  comment = "Variable encoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 326
  comment = "Variable encoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 258
  comment = "Variable decoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 280
  comment = "Variable decoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_extension.go"
  fileline = 268
  comment = "Variable decoder shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/reflect_struct_decoder.go"
  fileline = 537
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/urfave/cli/command.go"
  fileline = 184
  comment = "Variable set shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/text_parser.go"
  fileline = 770
  comment = "Variable tok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_skip_sloppy.go"
  fileline = 108
  comment = "Variable j shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/properties.go"
  fileline = 77
  comment = "Variable fi shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1268
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1151
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1150
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1451
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1452
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1317
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1317
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1332
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1333
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 705
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 706
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 689
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 689
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 755
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 755
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 772
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 771
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 887
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 887
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 903
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1091
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1092
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1392
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1393
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 837
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 838
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 821
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 821
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1209
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1210
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1031
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1032
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1015
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 1015
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 967
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 951
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/golang/protobuf/proto/table_unmarshal.go"
  fileline = 951
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_int.go"
  fileline = 101
  comment = "Variable val shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_int.go"
  fileline = 43
  comment = "Variable val shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_int.go"
  fileline = 223
  comment = "Variable val shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_int.go"
  fileline = 72
  comment = "Variable val shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/shiena/ansicolor/ansicolor_windows.go"
  fileline = 393
  comment = "Variable nw shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/modern-go/reflect2/safe_map.go"
  fileline = 54
  comment = "Variable ptr shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_str.go"
  fileline = 13
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/json-iterator/go/iter_str.go"
  fileline = 134
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/peterh/liner/line.go"
  fileline = 471
  comment = "Variable history shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/peterh/liner/line.go"
  fileline = 471
  comment = "Variable positions shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/astaxie/beego/session/session.go"
  fileline = 168
  comment = "Variable errs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/GeertJohan/go.rice/virtual.go"
  fileline = 88
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/GeertJohan/go.rice/virtual.go"
  fileline = 213
  comment = "Variable offset shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/astaxie/beego/session/sess_file.go"
  fileline = 256
  comment = "Variable ss shadows a variable of the same name declared in an outer scope."
