repo = "github.com/rakyll/hey"
rule = "codelingo/go/break-select-in-for"
sha = "f3676ef133bcbda356147da8c0ded4d36d1d28f5"

[[issues]]
  filepath = "vendor/golang.org/x/net/http2/server.go"
  fileline = 812
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
