repo = "github.com/morya/bigotim"
rule = "codelingo/go/default-in-type-switch"
sha = "de72eda6f7ff4ea04eda3060a0a2ca73597ca313"

[[issues]]
  fileline = 18
  filepath = "cmd/server/coder.go"
  fixed = false
  ignored = "unused code"

[[issues]]
  fileline = 23
  filepath = "cmd/client/coder.go"
  fixed = false
  ignored = "unused code"
