repo = "github.com/uber-go/zap"
rule = "codelingo/go/default-in-type-switch"
sha = "ec2dc456c680236892af2c645172713e1c4e1acd"

[[issues]]
  filepath = "zapcore/error.go"
  fileline = 49
  comment = "Always include a default case when using a type switch."
