repo = "github.com/jesseduffield/lazydocker"
rule = "codelingo/go/shadowed-variable"
sha = "22ab84043937cdbb9dcb08518dc9adf7f2c7a68b"

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1211
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1212
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1195
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1195
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1389
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1390
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1331
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1330
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1448
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1001
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1001
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1017
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1018
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1083
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1067
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1067
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1147
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1131
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1131
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 869
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 869
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 885
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 886
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 935
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 935
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 952
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 951
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1272
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1271
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1497
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1497
  comment = "Variable x shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1512
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1513
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1631
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1632
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1572
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_unmarshal.go"
  fileline = 1573
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/golang.org/x/xerrors/fmt.go"
  fileline = 53
  comment = "Variable frame shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/golang.org/x/xerrors/fmt.go"
  fileline = 52
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_marshal.go"
  fileline = 2938
  comment = "Variable siz shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_marshal.go"
  fileline = 2939
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/table_marshal.go"
  fileline = 2970
  comment = "Variable siz shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/golang.org/x/sys/unix/syscall_freebsd.go"
  fileline = 173
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/docker/go-connections/nat/parse.go"
  fileline = 39
  comment = "Variable start shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/docker/go-connections/nat/parse.go"
  fileline = 40
  comment = "Variable end shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/sirupsen/logrus/entry.go"
  fileline = 171
  comment = "Variable pcs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/gogo/protobuf/proto/properties.go"
  fileline = 82
  comment = "Variable fi shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/scannerc.go"
  fileline = 1275
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/gui/containers_panel.go"
  fileline = 189
  comment = "Variable mainView shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/gui/layout.go"
  fileline = 84
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/gui/layout.go"
  fileline = 276
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/parserc.go"
  fileline = 861
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/parserc.go"
  fileline = 906
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/parserc.go"
  fileline = 772
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/parserc.go"
  fileline = 677
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/jesseduffield/yaml/parserc.go"
  fileline = 581
  comment = "Variable token shadows a variable of the same name declared in an outer scope."
