repo = "github.com/coreybutler/nvm-windows"
rule = "codelingo/go/unchecked-type-assertion"
sha = "88353cfcea140e02e2b13584fd89454adc9f52b3"

[[issues]]
  filepath = "src/nvm/node/node.go"
  fileline = 141
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
