repo = "github.com/SimonWaldherr/ups"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "d3e0fc2485f52550d12a96ae00b44a25738eb42e"

[[issues]]
  filepath = "ups.go"
  fileline = 534

[[issues]]
  filepath = "ups.go"
  fileline = 534

[[issues]]
  filepath = "ups.go"
  fileline = 534

[[issues]]
  filepath = "ups.go"
  fileline = 534

[[issues]]
  filepath = "ups.go"
  fileline = 521

[[issues]]
  filepath = "ups.go"
  fileline = 523

[[issues]]
  filepath = "ups.go"
  fileline = 521

[[issues]]
  filepath = "ups.go"
  fileline = 523

[[issues]]
  filepath = "ups.go"
  fileline = 523

[[issues]]
  filepath = "ups.go"
  fileline = 510

[[issues]]
  filepath = "ups.go"
  fileline = 532

[[issues]]
  filepath = "ups.go"
  fileline = 523

[[issues]]
  filepath = "ups.go"
  fileline = 523

[[issues]]
  filepath = "ups.go"
  fileline = 522

[[issues]]
  filepath = "ups.go"
  fileline = 522

[[issues]]
  filepath = "ups.go"
  fileline = 522

[[issues]]
  filepath = "ups.go"
  fileline = 524

[[issues]]
  filepath = "ups.go"
  fileline = 522

[[issues]]
  filepath = "ups.go"
  fileline = 524

[[issues]]
  filepath = "ups.go"
  fileline = 510

[[issues]]
  filepath = "ups.go"
  fileline = 521

[[issues]]
  filepath = "ups.go"
  fileline = 510

[[issues]]
  filepath = "ups.go"
  fileline = 510

[[issues]]
  filepath = "ups.go"
  fileline = 532

[[issues]]
  filepath = "ups.go"
  fileline = 521

[[issues]]
  filepath = "ups.go"
  fileline = 510

[[issues]]
  filepath = "ups.go"
  fileline = 526

[[issues]]
  filepath = "ups.go"
  fileline = 521

[[issues]]
  filepath = "ups.go"
  fileline = 522

[[issues]]
  filepath = "ups.go"
  fileline = 467

[[issues]]
  filepath = "ups.go"
  fileline = 466

[[issues]]
  filepath = "ups.go"
  fileline = 467

[[issues]]
  filepath = "ups.go"
  fileline = 466

[[issues]]
  filepath = "ups.go"
  fileline = 466

[[issues]]
  filepath = "ups.go"
  fileline = 466

[[issues]]
  filepath = "ups.go"
  fileline = 467

[[issues]]
  filepath = "ups.go"
  fileline = 466

[[issues]]
  filepath = "ups.go"
  fileline = 542

[[issues]]
  filepath = "ups.go"
  fileline = 542

[[issues]]
  filepath = "ups.go"
  fileline = 541

[[issues]]
  filepath = "ups.go"
  fileline = 542

[[issues]]
  filepath = "ups.go"
  fileline = 542

[[issues]]
  filepath = "ups.go"
  fileline = 542

[[issues]]
  filepath = "ups.go"
  fileline = 465

[[issues]]
  filepath = "ups.go"
  fileline = 464

[[issues]]
  filepath = "ups.go"
  fileline = 465

[[issues]]
  filepath = "ups.go"
  fileline = 464

[[issues]]
  filepath = "ups.go"
  fileline = 464

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 492

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 493

[[issues]]
  filepath = "ups.go"
  fileline = 481

[[issues]]
  filepath = "ups.go"
  fileline = 491

[[issues]]
  filepath = "ups.go"
  fileline = 491

[[issues]]
  filepath = "ups.go"
  fileline = 482

[[issues]]
  filepath = "ups.go"
  fileline = 483

[[issues]]
  filepath = "ups.go"
  fileline = 481

[[issues]]
  filepath = "ups.go"
  fileline = 491

[[issues]]
  filepath = "ups.go"
  fileline = 483

[[issues]]
  filepath = "ups.go"
  fileline = 491

[[issues]]
  filepath = "ups.go"
  fileline = 498

[[issues]]
  filepath = "ups.go"
  fileline = 498

[[issues]]
  filepath = "ups.go"
  fileline = 484

[[issues]]
  filepath = "ups.go"
  fileline = 480

[[issues]]
  filepath = "ups.go"
  fileline = 483

[[issues]]
  filepath = "ups.go"
  fileline = 485

[[issues]]
  filepath = "ups.go"
  fileline = 482

[[issues]]
  filepath = "ups.go"
  fileline = 481

[[issues]]
  filepath = "ups.go"
  fileline = 481

[[issues]]
  filepath = "ups.go"
  fileline = 482

[[issues]]
  filepath = "ups.go"
  fileline = 491

[[issues]]
  filepath = "ups.go"
  fileline = 483

[[issues]]
  filepath = "ups.go"
  fileline = 482

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 555

[[issues]]
  filepath = "ups.go"
  fileline = 554

[[issues]]
  filepath = "ups.go"
  fileline = 495

[[issues]]
  filepath = "ups.go"
  fileline = 495

[[issues]]
  filepath = "ups.go"
  fileline = 495

[[issues]]
  filepath = "ups.go"
  fileline = 495

[[issues]]
  filepath = "ups.go"
  fileline = 495

[[issues]]
  filepath = "ups.go"
  fileline = 504

[[issues]]
  filepath = "ups.go"
  fileline = 504

[[issues]]
  filepath = "ups.go"
  fileline = 504

[[issues]]
  filepath = "ups.go"
  fileline = 504

[[issues]]
  filepath = "ups.go"
  fileline = 488

[[issues]]
  filepath = "ups.go"
  fileline = 488

[[issues]]
  filepath = "ups.go"
  fileline = 488

[[issues]]
  filepath = "ups.go"
  fileline = 488

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 552

[[issues]]
  filepath = "ups.go"
  fileline = 551

[[issues]]
  filepath = "ups.go"
  fileline = 529

[[issues]]
  filepath = "ups.go"
  fileline = 530

[[issues]]
  filepath = "ups.go"
  fileline = 529

[[issues]]
  filepath = "ups.go"
  fileline = 530

[[issues]]
  filepath = "ups.go"
  fileline = 479

[[issues]]
  filepath = "ups.go"
  fileline = 477

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 479

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 479

[[issues]]
  filepath = "ups.go"
  fileline = 477

[[issues]]
  filepath = "ups.go"
  fileline = 473

[[issues]]
  filepath = "ups.go"
  fileline = 477

[[issues]]
  filepath = "ups.go"
  fileline = 477

[[issues]]
  filepath = "ups.go"
  fileline = 479

[[issues]]
  filepath = "ups.go"
  fileline = 477

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 544

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 539

[[issues]]
  filepath = "ups.go"
  fileline = 501

[[issues]]
  filepath = "ups.go"
  fileline = 503

[[issues]]
  filepath = "ups.go"
  fileline = 533

[[issues]]
  filepath = "ups.go"
  fileline = 474

[[issues]]
  filepath = "ups.go"
  fileline = 474

[[issues]]
  filepath = "ups.go"
  fileline = 474

[[issues]]
  filepath = "ups.go"
  fileline = 472

[[issues]]
  filepath = "ups.go"
  fileline = 470

[[issues]]
  filepath = "ups.go"
  fileline = 472

[[issues]]
  filepath = "ups.go"
  fileline = 469

[[issues]]
  filepath = "ups.go"
  fileline = 472

[[issues]]
  filepath = "ups.go"
  fileline = 468

[[issues]]
  filepath = "ups.go"
  fileline = 468

[[issues]]
  filepath = "ups.go"
  fileline = 469

[[issues]]
  filepath = "ups.go"
  fileline = 468

[[issues]]
  filepath = "ups.go"
  fileline = 469

[[issues]]
  filepath = "ups.go"
  fileline = 470

[[issues]]
  filepath = "ups.go"
  fileline = 527

[[issues]]
  filepath = "ups.go"
  fileline = 527

[[issues]]
  filepath = "ups.go"
  fileline = 515

[[issues]]
  filepath = "ups.go"
  fileline = 515

[[issues]]
  filepath = "ups.go"
  fileline = 515

[[issues]]
  filepath = "ups.go"
  fileline = 515

[[issues]]
  filepath = "ups.go"
  fileline = 538

[[issues]]
  filepath = "ups.go"
  fileline = 538

[[issues]]
  filepath = "ups.go"
  fileline = 538

[[issues]]
  filepath = "ups.go"
  fileline = 514

[[issues]]
  filepath = "ups.go"
  fileline = 518

[[issues]]
  filepath = "ups.go"
  fileline = 518

[[issues]]
  filepath = "ups.go"
  fileline = 512

[[issues]]
  filepath = "ups.go"
  fileline = 514

[[issues]]
  filepath = "ups.go"
  fileline = 518

[[issues]]
  filepath = "ups.go"
  fileline = 514

[[issues]]
  filepath = "ups.go"
  fileline = 512

[[issues]]
  filepath = "ups.go"
  fileline = 57

[[issues]]
  filepath = "ups.go"
  fileline = 57

[[issues]]
  filepath = "ups.go"
  fileline = 48

[[issues]]
  filepath = "ups.go"
  fileline = 56

[[issues]]
  filepath = "ups.go"
  fileline = 52

[[issues]]
  filepath = "ups.go"
  fileline = 48

[[issues]]
  filepath = "ups.go"
  fileline = 48

[[issues]]
  filepath = "ups.go"
  fileline = 53

[[issues]]
  filepath = "ups.go"
  fileline = 47

[[issues]]
  filepath = "ups.go"
  fileline = 49

[[issues]]
  filepath = "ups.go"
  fileline = 55

[[issues]]
  filepath = "ups.go"
  fileline = 51

[[issues]]
  filepath = "ups.go"
  fileline = 52

[[issues]]
  filepath = "ups.go"
  fileline = 51

[[issues]]
  filepath = "ups.go"
  fileline = 52

[[issues]]
  filepath = "ups.go"
  fileline = 53

[[issues]]
  filepath = "ups.go"
  fileline = 47

[[issues]]
  filepath = "ups.go"
  fileline = 56

[[issues]]
  filepath = "ups.go"
  fileline = 49

[[issues]]
  filepath = "ups.go"
  fileline = 55
