repo = "github.com/tonyalaribe/converze-api"
rule = "codelingo/go/unchecked-type-assertion"
sha = "81f327385e55576139526c2fd86b8c5fb68b7458"

[[issues]]
  filepath = "web/middlewares.go"
  fileline = 148
