repo = "github.com/inconshreveable/ngrok"
rule = "codelingo/go/unchecked-type-assertion"
sha = "a8e7fa486348f391f4bdf241344d798297f953bc"

[[issues]]
  filepath = "src/ngrok/conn/conn.go"
  fileline = 42
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/server/tunnel.go"
  fileline = 115
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/controller.go"
  fileline = 152
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/conn/conn.go"
  fileline = 40
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/server/main.go"
  fileline = 87
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/views/web/http.go"
  fileline = 191
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/controller.go"
  fileline = 173
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/cache/lru.go"
  fileline = 240
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/model.go"
  fileline = 308
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/cache/lru.go"
  fileline = 162
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/controller.go"
  fileline = 196
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/msg/pack.go"
  fileline = 25
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/views/term/http.go"
  fileline = 73
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/views/web/http.go"
  fileline = 152
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/client/controller.go"
  fileline = 210
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "src/ngrok/server/control.go"
  fileline = 192
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
