repo = "github.com/caddyserver/caddy"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 50
  filepath = "caddyhttp/errors/errors_test.go"
  fixed = false
  ignored = "returned file discarded"
