repo = "github.com/future-architect/vuls"
rule = "codelingo/go/break-select-in-for"
sha = "5729ad6026bbe49eb3f570b54cb430265bf180fb"

[[issues]]
  filepath = "scan/serverapi.go"
  fileline = 252
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "scan/serverapi.go"
  fileline = 314
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"

[[issues]]
  filepath = "scan/serverapi.go"
  fileline = 454
  comment = "This `break` statement only breaks to the innermost select, rather than the parent `for` loop.\nThis is generally unexpected and can cause an active goroutine to leak.\nFix it by adding a label to the for loop and breaking to that instead.\n"
