repo = "github.com/SimonWaldherr/golibs"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 66

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 65

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 66

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 65

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 65

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 92

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 92

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 93

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 92

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 93

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 91

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 91

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 91

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 233

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 231

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 231

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 233

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 232

[[issues]]
  filepath = "re/re.go"
  fileline = 48

[[issues]]
  filepath = "re/re.go"
  fileline = 51

[[issues]]
  filepath = "re/re.go"
  fileline = 51

[[issues]]
  filepath = "re/re.go"
  fileline = 51

[[issues]]
  filepath = "re/re.go"
  fileline = 50

[[issues]]
  filepath = "re/re.go"
  fileline = 47

[[issues]]
  filepath = "re/re.go"
  fileline = 50

[[issues]]
  filepath = "re/re.go"
  fileline = 45

[[issues]]
  filepath = "re/re.go"
  fileline = 44

[[issues]]
  filepath = "re/re.go"
  fileline = 40

[[issues]]
  filepath = "re/re.go"
  fileline = 39

[[issues]]
  filepath = "re/re.go"
  fileline = 39

[[issues]]
  filepath = "re/re.go"
  fileline = 41

[[issues]]
  filepath = "re/re.go"
  fileline = 40

[[issues]]
  filepath = "re/re.go"
  fileline = 40

[[issues]]
  filepath = "re/re.go"
  fileline = 41

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 30

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 30

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 34

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 35

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 35

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 34

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 34

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 240

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 238

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 239

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 240

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 238

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 239

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 239

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 239

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 226

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 226

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 44

[[issues]]
  filepath = "cache/cache_test.go"
  fileline = 225

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 44

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 46

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 46

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 46

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 45

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 48

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 48

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 47

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 50

[[issues]]
  filepath = "examples/ring.go"
  fileline = 21

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 50

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 23

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 24

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 23

[[issues]]
  filepath = "rss/rss_test.go"
  fileline = 50

[[issues]]
  filepath = "examples/ring.go"
  fileline = 24

[[issues]]
  filepath = "examples/ring.go"
  fileline = 21

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 23

[[issues]]
  filepath = "examples/ring.go"
  fileline = 21

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 24

[[issues]]
  filepath = "examples/ring.go"
  fileline = 25

[[issues]]
  filepath = "examples/ring.go"
  fileline = 25

[[issues]]
  filepath = "examples/ring.go"
  fileline = 21

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 21

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 24

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 26

[[issues]]
  filepath = "examples/ring.go"
  fileline = 23

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "examples/ring.go"
  fileline = 23

[[issues]]
  filepath = "examples/ring.go"
  fileline = 22

[[issues]]
  filepath = "channel/example_test.go"
  fileline = 21

[[issues]]
  filepath = "channel/example_test.go"
  fileline = 21

[[issues]]
  filepath = "channel/example_test.go"
  fileline = 22

[[issues]]
  filepath = "channel/example_test.go"
  fileline = 22

[[issues]]
  filepath = "channel/example_test.go"
  fileline = 21

[[issues]]
  filepath = "channel/channel.go"
  fileline = 30

[[issues]]
  filepath = "channel/channel.go"
  fileline = 32

[[issues]]
  filepath = "channel/channel.go"
  fileline = 32

[[issues]]
  filepath = "channel/channel.go"
  fileline = 30

[[issues]]
  filepath = "channel/channel.go"
  fileline = 24

[[issues]]
  filepath = "channel/channel.go"
  fileline = 24

[[issues]]
  filepath = "channel/channel.go"
  fileline = 22

[[issues]]
  filepath = "channel/channel.go"
  fileline = 21

[[issues]]
  filepath = "channel/channel.go"
  fileline = 25

[[issues]]
  filepath = "channel/channel.go"
  fileline = 21

[[issues]]
  filepath = "channel/channel.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel.go"
  fileline = 22

[[issues]]
  filepath = "channel/channel.go"
  fileline = 22

[[issues]]
  filepath = "channel/channel.go"
  fileline = 23

[[issues]]
  filepath = "channel/channel.go"
  fileline = 25

[[issues]]
  filepath = "channel/channel.go"
  fileline = 28

[[issues]]
  filepath = "channel/channel.go"
  fileline = 24

[[issues]]
  filepath = "channel/channel.go"
  fileline = 23

[[issues]]
  filepath = "channel/channel.go"
  fileline = 29

[[issues]]
  filepath = "channel/channel.go"
  fileline = 28

[[issues]]
  filepath = "channel/channel.go"
  fileline = 25

[[issues]]
  filepath = "arg/arg.go"
  fileline = 45

[[issues]]
  filepath = "arg/arg.go"
  fileline = 47

[[issues]]
  filepath = "arg/arg.go"
  fileline = 45

[[issues]]
  filepath = "arg/arg.go"
  fileline = 47

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 25

[[issues]]
  filepath = "arg/arg.go"
  fileline = 47

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 25

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 24

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 24

[[issues]]
  filepath = "channel/channel_test.go"
  fileline = 24
