repo = "github.com/caddyserver/caddy"
rule = "codelingo/lomik-go-carbon/missing-stop-ticker"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 34
  filepath = "caddytls/crypto.go"
  fixed = false
  ignored = "fp. ticker passed on and stopped elsewhere"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 47
  filepath = "caddytls/crypto_test.go"
  fixed = false
  ignored = "fp. ticker passed on and stopped elsewhere"
