repo = "github.com/tonyalaribe/contact.info"
rule = "codelingo/go/unchecked-type-assertion"
sha = "84204a761618454769b0f2b506e27ab659011e77"

[[issues]]
  filepath = "contactinfo.go"
  fileline = 188

[[issues]]
  filepath = "contactinfo.go"
  fileline = 119

[[issues]]
  filepath = "contactinfo.go"
  fileline = 161

[[issues]]
  filepath = "contactinfo.go"
  fileline = 159

[[issues]]
  filepath = "contactinfo.go"
  fileline = 189

[[issues]]
  filepath = "contactinfo.go"
  fileline = 121

[[issues]]
  filepath = "contactinfo.go"
  fileline = 120

[[issues]]
  filepath = "contactinfo.go"
  fileline = 117

[[issues]]
  filepath = "contactinfo.go"
  fileline = 160

[[issues]]
  filepath = "contactinfo.go"
  fileline = 92
