repo = "github.com/grpc-ecosystem/grpc-gateway"
rule = "codelingo/go/reassigned-error"
sha = "da18680cd10b7acf76a7175b2b0523fda9fa188c"

[[issues]]
  filepath = "examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go"
  fileline = 1952
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "examples/internal/proto/examplepb/a_bit_of_everything.pb.gw.go"
  fileline = 1913
  comment = "Error was not checked before reassignment"
