repo = "github.com/yudai/gotty"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "a080c85cbc59226c94c6941ad8c395232d72d517"

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 70
  comment = "The variable errs should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 70
  comment = "The variable error should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 80
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 71
  comment = "The variable make should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 71
  comment = "The variable bufferSize should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 71
  comment = "The variable byte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 71
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 75
  comment = "The variable ErrSlaveClosed should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 78
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 73
  comment = "The variable Read should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 79
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 78
  comment = "The variable buffer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 73
  comment = "The variable buffer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 78
  comment = "The variable handleSlaveReadEvent should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 73
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 74
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 73
  comment = "The variable slave should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 65
  comment = "The variable cmd should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 65
  comment = "The variable Wait should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 65
  comment = "The variable lcmd should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 61
  comment = "The variable Close should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 61
  comment = "The variable pty should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 61
  comment = "The variable lcmd should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 62
  comment = "The variable close should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 62
  comment = "The variable ptyClosed should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "backend/localcommand/local_command.go"
  fileline = 62
  comment = "The variable lcmd should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 158
  comment = "The variable cctx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 156
  comment = "The variable gracefullCtx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 156
  comment = "The variable opts should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 157
  comment = "The variable Shutdown should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 156
  comment = "The variable Done should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 157
  comment = "The variable Background should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 157
  comment = "The variable context should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 157
  comment = "The variable srv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 158
  comment = "The variable Done should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable ctx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable srv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable WithGracefullContext should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable gCtx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable errs should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable Run should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 102
  comment = "The variable server should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 92
  comment = "The variable ErrMasterClosed should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 97
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 95
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 90
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 96
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 95
  comment = "The variable handleMasterReadEvent should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 90
  comment = "The variable masterConn should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 90
  comment = "The variable Read should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 90
  comment = "The variable buffer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 91
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 95
  comment = "The variable buffer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 87
  comment = "The variable errs should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 87
  comment = "The variable error should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 88
  comment = "The variable bufferSize should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 88
  comment = "The variable wt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 88
  comment = "The variable byte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty.go"
  fileline = 88
  comment = "The variable make should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 92
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 92
  comment = "The variable Fatalf should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 92
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 90
  comment = "The variable Run should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 89
  comment = "The variable wg should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 89
  comment = "The variable Done should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 91
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 90
  comment = "The variable ctx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 90
  comment = "The variable dt should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 26
  comment = "The variable ctx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 25
  comment = "The variable cancel should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 24
  comment = "The variable counter should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 24
  comment = "The variable C should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 26
  comment = "The variable Done should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/handlers.go"
  fileline = 24
  comment = "The variable timer should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 150
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 150
  comment = "The variable srvErr should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 147
  comment = "The variable listener should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 147
  comment = "The variable Serve should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 147
  comment = "The variable srv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 139
  comment = "The variable EnableTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 139
  comment = "The variable server should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 139
  comment = "The variable options should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 149
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 149
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 140
  comment = "The variable Expand should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 143
  comment = "The variable Printf should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 142
  comment = "The variable log should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 141
  comment = "The variable homedir should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 141
  comment = "The variable Expand should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 140
  comment = "The variable server should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 141
  comment = "The variable TLSKeyFile should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 145
  comment = "The variable srv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 140
  comment = "The variable TLSCrtFile should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 141
  comment = "The variable options should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 142
  comment = "The variable Printf should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 145
  comment = "The variable ServeTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 140
  comment = "The variable options should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 141
  comment = "The variable server should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 140
  comment = "The variable homedir should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 143
  comment = "The variable log should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "server/server.go"
  fileline = 145
  comment = "The variable listener should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 37
  comment = "The variable Fatalf should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 37
  comment = "The variable err should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 37
  comment = "The variable t should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 34
  comment = "The variable Done should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 35
  comment = "The variable ctx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 34
  comment = "The variable wg should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 35
  comment = "The variable Run should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 36
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "webtty/webtty_test.go"
  fileline = 35
  comment = "The variable dt should be passed in as arguments to go-routines to avoid race conditions."
