repo = "github.com/andrejsim/golangprimer"
rule = "unsafe-go-routine-variables"
sha = "caf7babff893418d8e6368771e11417179f48cb1"

[[issues]]
  fileline = 42
  filepath = "hello.go"
  fixed = false
  ignored = "fp. is a chan"
