repo = "github.com/arthurkiller/rollingwriter"
rule = "unsafe-go-routine-variables"
sha = "0c781a15588e265e57e6bc5c4a0efd070a72a6ac"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 260
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 264
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 260
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 260
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 260
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 260
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 273
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 275
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 276
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 273
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 275
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 273
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 265
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 265
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 265
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 261
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 261
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 261
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 258
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 258
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 259
  filepath = "writer.go"
  fixed = false
  ignored = "fp. var not referenced anywhere else"

[[issues]]
  fileline = 270
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 259
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 258
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 258
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 270
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 270
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 259
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 271
  filepath = "writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 55
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 52
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 55
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 54
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 55
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 52
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 51
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 59
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 62
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 65
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 65
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 62
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 59
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 68
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 62
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 65
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 65
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 65
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 62
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 61
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 66
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 66
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 66
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 66
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 66
  filepath = "manager.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "demo/writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "demo/writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "demo/writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "demo/writer.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 53
  filepath = "demo/writer.go"
  fixed = false
  ignored = "fp"
