repo = "github.com/gadelkareem/cachita"
rule = "unsafe-go-routine-variables"
sha = "27c05434ad48d5cbb92e0af613152ed5ac17dbe5"

[[issues]]
  fileline = 61
  filepath = "cache.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 60
  filepath = "cache.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 60
  filepath = "cache.go"
  fixed = false
  ignored = "fp"
