repo = "github.com/nickysemenza/machelper"
rule = "unsafe-go-routine-variables"
sha = "4d52fc2423dbcf975a130b0257f13a35bc8d999e"

[[issues]]
  fileline = 115
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 115
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 115
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 118
  filepath = "main.go"
  fixed = true
  ignored = ""

[[issues]]
  fileline = 113
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 112
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 114
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 113
  filepath = "main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 112
  filepath = "main.go"
  fixed = false
  ignored = "fp"
