repo = "github.com/rfjakob/gocryptfs-microbenchmarks"
rule = "unsafe-go-routine-variables"
sha = "e382da4d28a310b97466c69d6a996c62f05ae3bf"

[[issues]]
  fileline = 48
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = true
  ignored = ""

[[issues]]
  fileline = 48
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 49
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 48
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 48
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 49
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 70
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 71
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 70
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 71
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 70
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 120
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 121
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 120
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 120
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"

[[issues]]
  fileline = 121
  filepath = "parallel_gcm/pgcm_test.go"
  fixed = false
  ignored = "dup"
