repo = "github.com/sundy-li/sem_spider_baidu"
rule = "unsafe-go-routine-variables"
sha = "e4e27c8cbcdd426477505f026a8a275525ccbd74"

[[issues]]
  filepath = "service/spider.go"
  fileline = 229

[[issues]]
  filepath = "service/spider.go"
  fileline = 228

[[issues]]
  filepath = "service/spider.go"
  fileline = 229

[[issues]]
  filepath = "service/spider.go"
  fileline = 228

[[issues]]
  filepath = "service/spider.go"
  fileline = 141

[[issues]]
  filepath = "service/spider.go"
  fileline = 143

[[issues]]
  filepath = "service/spider.go"
  fileline = 140

[[issues]]
  filepath = "service/spider.go"
  fileline = 142

[[issues]]
  filepath = "service/spider.go"
  fileline = 143

[[issues]]
  filepath = "service/spider.go"
  fileline = 140

[[issues]]
  filepath = "service/spider.go"
  fileline = 184

[[issues]]
  filepath = "service/spider.go"
  fileline = 184

[[issues]]
  filepath = "service/spider.go"
  fileline = 185

[[issues]]
  filepath = "service/spider.go"
  fileline = 185

[[issues]]
  filepath = "service/spider.go"
  fileline = 133

[[issues]]
  filepath = "service/spider.go"
  fileline = 135

[[issues]]
  filepath = "service/spider.go"
  fileline = 133

[[issues]]
  filepath = "service/spider.go"
  fileline = 134

[[issues]]
  filepath = "service/spider.go"
  fileline = 136

[[issues]]
  filepath = "service/spider.go"
  fileline = 136
