repo = "github.com/apex/apex"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "16c08f0eb344e00f7c8353483467230efc3e586b"

[[issues]]
  filepath = "project/project.go"
  fileline = 108
  comment = "Close the file when you are done"

[[issues]]
  filepath = "function/function.go"
  fileline = 211
  comment = "Close the file when you are done"
