repo = "github.com/astaxie/beego"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "0cd80525e7e34d7f36965341184afda083567153"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 46
  filepath = "logs/multifile_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 36
  filepath = "staticfile_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 93
  filepath = "logs/file_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 60
  filepath = "logs/file_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 68
  filepath = "utils/file.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 46
  filepath = "staticfile_test.go"
  fixed = true
  ignored = ""

[[issues]]
  comment = "Close the file when you are done"
  fileline = 30
  filepath = "staticfile_test.go"
  fixed = true
  ignored = ""
