repo = "github.com/iikira/BaiduPCS-Go"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "52394a677126a284baea7199271838037a79342f"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 174
  filepath = "vendor/github.com/astaxie/beego/utils/mail.go"
  fixed = false
  ignored = "fp. handed off as io.Reader"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 22
  filepath = "vendor/github.com/daaku/go.zipexe/zipexe.go"
  fixed = false
  ignored = "fp. file is returned"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 68
  filepath = "vendor/github.com/astaxie/beego/utils/file.go"
  fixed = false
  ignored = "in vendor"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 271
  filepath = "vendor/github.com/GeertJohan/go.rice/box.go"
  fixed = false
  ignored = "in vendor"
