repo = "github.com/cyfdecyf/cow"
rule = "codelingo/go/shadowed-variable"
sha = "41c0fb157c8b939b724ae0d58dad3a1b7cd2e811"

[[issues]]
  filepath = "http.go"
  fileline = 522
  comment = "Variable line shadows a variable of the same name declared in an outer scope."
