repo = "github.com/sirupsen/logrus"
rule = "codelingo/go/default-in-type-switch"
sha = "7ea96a3284ed9d25de5056804d60426cb75833c7"

[[issues]]
  filepath = "terminal_check_windows.go"
  fileline = 14
  comment = "Always include a default case when using a type switch."
