repo = "github.com/helm/helm"
rule = "codelingo/go/unchecked-type-assertion"
sha = "ec1d1a3d3eb672232f896f9d3b3d0797e4f519e3"

[[issues]]
  filepath = "pkg/kube/wait.go"
  fileline = 350
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/install_test.go"
  fileline = 349
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/values_test.go"
  fileline = 138
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/kube/wait.go"
  fileline = 63
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/helm/helm.go"
  fileline = 96
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/dependencies_test.go"
  fileline = 225
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/values_test.go"
  fileline = 142
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/dependencies.go"
  fileline = 236
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/dependencies.go"
  fileline = 237
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/strvals/parser.go"
  fileline = 211
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/strvals/parser.go"
  fileline = 296
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/upgrade_test.go"
  fileline = 126
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/dependencies.go"
  fileline = 234
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/jsonschema.go"
  fileline = 44
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/install_test.go"
  fileline = 331
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/strvals/parser_test.go"
  fileline = 61
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/upgrade_test.go"
  fileline = 51
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/upgrade_test.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "cmd/helm/load_plugins.go"
  fileline = 106
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/install_test.go"
  fileline = 369
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/values_test.go"
  fileline = 115
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/upgrade_test.go"
  fileline = 73
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/coalesce.go"
  fileline = 74
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/action/install_test.go"
  fileline = 278
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/chartutil/coalesce.go"
  fileline = 45
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/strvals/parser.go"
  fileline = 173
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
