repo = "github.com/zyedidia/micro"
rule = "codelingo/go/unchecked-type-assertion"
sha = "943ea15fa3a9a9577c7b4b52307c0176606fea27"

[[issues]]
  filepath = "internal/action/actions.go"
  fileline = 148
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "tools/testgen.go"
  fileline = 38
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 382
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 201
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/bufpane.go"
  fileline = 296
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 300
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 171
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/actions.go"
  fileline = 147
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/bindings.go"
  fileline = 61
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/buffer/buffer.go"
  fileline = 924
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 315
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/tab.go"
  fileline = 201
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/buffer/settings.go"
  fileline = 39
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/rawpane.go"
  fileline = 30
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/actions.go"
  fileline = 173
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/buffer/buffer.go"
  fileline = 546
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/display/bufwindow.go"
  fileline = 463
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/actions.go"
  fileline = 1511
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/tab.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/actions.go"
  fileline = 174
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/action/infopane.go"
  fileline = 41
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/highlight/parser.go"
  fileline = 304
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "internal/display/bufwindow.go"
  fileline = 198
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
