repo = "github.com/golang/groupcache"
rule = "codelingo/go/ticker-in-for-select"
sha = "8c9f03a8e57eb486e42badaed3fb287da51807ba"

[[issues]]
  filepath = "groupcache_test.go"
  fileline = 118
  comment = "Make one ticker as opposed to making a new timer each iteration."

[[issues]]
  filepath = "groupcache_test.go"
  fileline = 162
  comment = "Make one ticker as opposed to making a new timer each iteration."
