repo = "github.com/buger/goreplay"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "ffc1a09ca1e465dc1b67efc151dab2771e1086c7"

[[issues]]
  filepath = "input_file.go"
  fileline = 75
  comment = "Close the file when you are done"
