repo = "github.com/gadelkareem/go-helpers"
rule = "codelingo/lomik-go-carbon/missing-stop-ticker"
sha = "37da31be3be96a995f9510f9c34c088bc4890dda"

[[issues]]
  filepath = "helpers.go"
  fileline = 185
