repo = "github.com/gadelkareem/go-helpers"
rule = "missing-stop-ticker"
sha = "37da31be3be96a995f9510f9c34c088bc4890dda"

[[issues]]
  fileline = 185
  filepath = "helpers.go"
  fixed = false
  ignored = "goroutine never exits. runs for prog duration"
