repo = "github.com/gadelkareem/elhabash"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "858e38187272b6d2394ad7ec4068ccf069a1d1be"

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 84

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 83

[[issues]]
  filepath = "snapshot.go"
  fileline = 82

[[issues]]
  filepath = "snapshot.go"
  fileline = 88

[[issues]]
  filepath = "snapshot.go"
  fileline = 89

[[issues]]
  filepath = "snapshot.go"
  fileline = 81

[[issues]]
  filepath = "snapshot.go"
  fileline = 89

[[issues]]
  filepath = "snapshot.go"
  fileline = 81

[[issues]]
  filepath = "snapshot.go"
  fileline = 81

[[issues]]
  filepath = "snapshot.go"
  fileline = 82

[[issues]]
  filepath = "snapshot.go"
  fileline = 81

[[issues]]
  filepath = "snapshot.go"
  fileline = 85

[[issues]]
  filepath = "snapshot.go"
  fileline = 85

[[issues]]
  filepath = "snapshot.go"
  fileline = 85

[[issues]]
  filepath = "fetch.go"
  fileline = 1011

[[issues]]
  filepath = "fetch.go"
  fileline = 1011

[[issues]]
  filepath = "fetch.go"
  fileline = 1012

[[issues]]
  filepath = "fetch.go"
  fileline = 1012

[[issues]]
  filepath = "fetch.go"
  fileline = 1010

[[issues]]
  filepath = "fetch.go"
  fileline = 1010

[[issues]]
  filepath = "fetch.go"
  fileline = 1010

[[issues]]
  filepath = "fetch.go"
  fileline = 1010

[[issues]]
  filepath = "fetch.go"
  fileline = 1010

[[issues]]
  filepath = "fetch.go"
  fileline = 1012

[[issues]]
  filepath = "fetch.go"
  fileline = 1003

[[issues]]
  filepath = "fetch.go"
  fileline = 1008

[[issues]]
  filepath = "fetch.go"
  fileline = 1009

[[issues]]
  filepath = "fetch.go"
  fileline = 1008

[[issues]]
  filepath = "fetch.go"
  fileline = 1003

[[issues]]
  filepath = "fetch.go"
  fileline = 1003

[[issues]]
  filepath = "fetch.go"
  fileline = 1002

[[issues]]
  filepath = "fetch.go"
  fileline = 1009

[[issues]]
  filepath = "fetch.go"
  fileline = 1003

[[issues]]
  filepath = "fetch.go"
  fileline = 1008

[[issues]]
  filepath = "fetch.go"
  fileline = 1008

[[issues]]
  filepath = "fetch.go"
  fileline = 1009

[[issues]]
  filepath = "fetch.go"
  fileline = 1002

[[issues]]
  filepath = "fetch.go"
  fileline = 1009

[[issues]]
  filepath = "fetch.go"
  fileline = 1001

[[issues]]
  filepath = "fetch.go"
  fileline = 1001

[[issues]]
  filepath = "fetch.go"
  fileline = 1009

[[issues]]
  filepath = "fetch.go"
  fileline = 1002

[[issues]]
  filepath = "fetch.go"
  fileline = 992

[[issues]]
  filepath = "fetch.go"
  fileline = 1008

[[issues]]
  filepath = "fetch.go"
  fileline = 992

[[issues]]
  filepath = "fetch.go"
  fileline = 1001

[[issues]]
  filepath = "fetch.go"
  fileline = 993

[[issues]]
  filepath = "fetch.go"
  fileline = 994

[[issues]]
  filepath = "fetch.go"
  fileline = 993

[[issues]]
  filepath = "fetch.go"
  fileline = 995

[[issues]]
  filepath = "fetch.go"
  fileline = 994

[[issues]]
  filepath = "fetch.go"
  fileline = 993

[[issues]]
  filepath = "fetch.go"
  fileline = 994

[[issues]]
  filepath = "fetch.go"
  fileline = 993

[[issues]]
  filepath = "fetch.go"
  fileline = 994

[[issues]]
  filepath = "fetch.go"
  fileline = 996

[[issues]]
  filepath = "fetch.go"
  fileline = 996

[[issues]]
  filepath = "fetch.go"
  fileline = 996

[[issues]]
  filepath = "fetch.go"
  fileline = 1004

[[issues]]
  filepath = "fetch.go"
  fileline = 1004

[[issues]]
  filepath = "fetch.go"
  fileline = 1004

[[issues]]
  filepath = "fetch.go"
  fileline = 1004

[[issues]]
  filepath = "fetch.go"
  fileline = 247

[[issues]]
  filepath = "fetch.go"
  fileline = 249

[[issues]]
  filepath = "fetch.go"
  fileline = 247

[[issues]]
  filepath = "fetch.go"
  fileline = 250

[[issues]]
  filepath = "fetch.go"
  fileline = 248

[[issues]]
  filepath = "fetch.go"
  fileline = 250

[[issues]]
  filepath = "fetch.go"
  fileline = 246

[[issues]]
  filepath = "fetch.go"
  fileline = 248

[[issues]]
  filepath = "fetch.go"
  fileline = 249
