repo = "github.com/astaxie/beego"
rule = "codelingo/go/shadowed-variable"
sha = "0cd80525e7e34d7f36965341184afda083567153"

[[issues]]
  filepath = "migration/migration.go"
  fileline = 141
  comment = "Variable p shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 906
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 581
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 677
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 772
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 861
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "session/session.go"
  fileline = 183
  comment = "Variable errs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/db.go"
  fileline = 999
  comment = "Variable sep shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "session/sess_file.go"
  fileline = 264
  comment = "Variable ss shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "staticfile.go"
  fileline = 117
  comment = "Variable reader shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm_raw.go"
  fileline = 421
  comment = "Variable sInd shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/acme/autocert/renewal.go"
  fileline = 99
  comment = "Variable state shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tree.go"
  fileline = 362
  comment = "Variable i shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tree.go"
  fileline = 296
  comment = "Variable i shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/scannerc.go"
  fileline = 1275
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm_test.go"
  fileline = 696
  comment = "Variable id shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm_test.go"
  fileline = 732
  comment = "Variable id shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm_test.go"
  fileline = 690
  comment = "Variable id shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm_test.go"
  fileline = 709
  comment = "Variable id shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "session/memcache/sess_memcache.go"
  fileline = 133
  comment = "Variable rs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "orm/orm.go"
  fileline = 145
  comment = "Variable id shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/golang.org/x/crypto/acme/acme.go"
  fileline = 203
  comment = "Variable cert shadows a variable of the same name declared in an outer scope."
