repo = "github.com/coreybutler/nvm-windows"
rule = "codelingo/go/default-in-type-switch"
sha = "88353cfcea140e02e2b13584fd89454adc9f52b3"

[[issues]]
  filepath = "src/nvm/node/node.go"
  fileline = 141
  comment = "Always include a default case when using a type switch."
