repo = "github.com/labstack/echo"
rule = "codelingo/go/unchecked-type-assertion"
sha = "fc4b1c0a830f194bf6334d2b3e61d92cccebb2be"

[[issues]]
  filepath = "router_test.go"
  fileline = 794
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 918
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 705
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 54
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 584
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 544
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1193
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1088
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt.go"
  fileline = 198
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1064
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1224
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/body_limit_test.go"
  fileline = 37
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 319
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 741
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 638
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 208
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 50
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "echo.go"
  fileline = 603
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 815
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 836
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 222
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 37
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 164
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 808
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 801
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 829
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 698
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 203
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "echo.go"
  fileline = 662
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1073
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 684
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 181
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 326
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 254
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 726
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 416
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1245
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 49
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 861
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/key_auth_test.go"
  fileline = 38
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/body_limit_test.go"
  fileline = 76
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 236
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 347
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 869
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 294
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1060
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 886
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 132
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 564
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 853
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 55
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 316
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 337
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1068
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 878
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 533
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 281
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 590
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 399
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 712
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 99
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 357
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/body_limit_test.go"
  fileline = 53
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1201
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 941
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/static_test.go"
  fileline = 43
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 306
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 894
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1213
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 774
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1218
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 65
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 170
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 610
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1197
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 521
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/basic_auth_test.go"
  fileline = 69
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 192
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/key_auth_test.go"
  fileline = 43
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 229
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1205
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1189
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1184
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 822
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/basic_auth_test.go"
  fileline = 57
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 51
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/logger.go"
  fileline = 121
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/body_limit.go"
  fileline = 82
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router.go"
  fileline = 311
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 312
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 363
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 384
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 772
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 939
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1209
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1075
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 960
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 230
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 143
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 269
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 1054
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 154
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/basic_auth_test.go"
  fileline = 63
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router_test.go"
  fileline = 760
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 320
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "context_test.go"
  fileline = 215
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
