repo = "github.com/containous/traefik"
rule = "codelingo/go/ticker-in-for-select"
sha = "16c48071621ac2f38bd02d55854574f384c913f0"

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 139
  filepath = "pkg/healthcheck/healthcheck_test.go"
  fixed = false
  ignored = "deterministic timer"
