repo = "github.com/mrcrowl/swarm"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "1611adb62c5c96673030783311328ecd35ea05b6"

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 48

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 50

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 48

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 50

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 49

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 48

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 49

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 48

[[issues]]
  filepath = "web/SocketHub.go"
  fileline = 48
