repo = "github.com/wagoodman/dive"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "c6bb2372a8be13a80a81c00c04f9724970c0ae60"

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 94
  comment = "The variable int should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 96
  comment = "The variable refTrees should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 96
  comment = "The variable len should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 96
  comment = "The variable cmp should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 92
  comment = "The variable close should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 92
  comment = "The variable indexes should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 102
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 101
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 105
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 104
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 108
  comment = "The variable indexes should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 98
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 100
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 108
  comment = "The variable TreeIndexKey should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 125
  comment = "The variable close should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 129
  comment = "The variable len should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 125
  comment = "The variable indexes should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 127
  comment = "The variable int should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 129
  comment = "The variable refTrees should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 129
  comment = "The variable cmp should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 131
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 140
  comment = "The variable indexes should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 132
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 140
  comment = "The variable TreeIndexKey should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 133
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "dive/filetree/comparer.go"
  fileline = 134
  comment = "The variable selectIdx should be passed in as arguments to go-routines to avoid race conditions."
