repo = "github.com/nats-io/nats-server"
rule = "codelingo/go/non-directional-chan"
sha = "8c8d6f88466bb7161a5246892ea6ff89ac9547c3"

[[issues]]
  filepath = "test/bench_test.go"
  fileline = 1348
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/client_test.go"
  fileline = 71
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/server.go"
  fileline = 1353
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "test/bench_test.go"
  fileline = 918
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/gateway_test.go"
  fileline = 145
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 3472
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2844
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "test/bench_test.go"
  fileline = 149
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2673
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 3456
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2928
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/gateway.go"
  fileline = 431
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2918
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "test/bench_test.go"
  fileline = 1062
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2854
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/route.go"
  fileline = 1353
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/client_test.go"
  fileline = 101
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/leafnode.go"
  fileline = 318
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "test/tls_test.go"
  fileline = 858
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/routes_test.go"
  fileline = 745
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "vendor/github.com/nats-io/nats.go/nats.go"
  fileline = 2893
  comment = "Returned channels or channel arguments should generally have a direction."

[[issues]]
  filepath = "server/route.go"
  fileline = 1491
  comment = "Returned channels or channel arguments should generally have a direction."
