repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/insecure-http-connection"
sha = "094b3fdb393ff8eab16ec293bf49513213955523"

[[issues]]
  filepath = "gin_test.go"
  fileline = 252

[[issues]]
  filepath = "gin_test.go"
  fileline = 134

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 26
