repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/insecure-http-connection"
sha = "a71af9c144f9579f6dbe945341c1df37aaf09c0d"

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 26
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "gin_test.go"
  fileline = 252
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."

[[issues]]
  filepath = "gin_test.go"
  fileline = 134
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
