repo = "github.com/v2ray/v2ray-core"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "c44dd395072f77e0e51a4258a159d2dbbc340371"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 139
  filepath = "infra/control/verify.go"
  fixed = false
  ignored = "passed on as io.Reader"

[[issues]]
  comment = "Close the file when you are done"
  fileline = 144
  filepath = "infra/control/verify.go"
  fixed = false
  ignored = "passed on as io.Reader"
