repo = "github.com/ipfs/go-ipfs"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "4acb15d52b26bc71071f44f71ef0a72b547cf855"

[[issues]]
  filepath = "cmd/ipfs/runmain_test.go"
  fileline = 27
  comment = "Close the file when you are done"

[[issues]]
  filepath = "keystore/keystore.go"
  fileline = 154
  comment = "Close the file when you are done"
