repo = "github.com/iikira/BaiduPCS-Go"
rule = "codelingo/go/pointer-leaves-method"
sha = "52394a677126a284baea7199271838037a79342f"

[[issues]]
  filepath = "vendor/golang.org/x/sys/windows/dll_windows.go"
  fileline = 91
  comment = "The receiver pointer is returned from this method. Make a copy instead."
