repo = "github.com/murphy0202/doodle"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "cec92093d61c1479f5a1ce5a5b86f5f152ec7b56"

[[issues]]
  filepath = "birthday2019/surprise.go"
  fileline = 162

[[issues]]
  filepath = "birthday2019/surprise.go"
  fileline = 162

[[issues]]
  filepath = "birthday2019/surprise.go"
  fileline = 162

[[issues]]
  filepath = "summer2019/summer.go"
  fileline = 489

[[issues]]
  filepath = "summer2019/summer.go"
  fileline = 489

[[issues]]
  filepath = "summer2019/summer.go"
  fileline = 489

[[issues]]
  filepath = "cheers2019/cheers.go"
  fileline = 270

[[issues]]
  filepath = "cheers2019/cheers.go"
  fileline = 270

[[issues]]
  filepath = "cheers2019/cheers.go"
  fileline = 270
