repo = "github.com/nickysemenza/hyperion"
rule = "codelingo/go/shadowed-variable"
sha = "1392edb4e04de42fd7988a6542db9b38092af3fa"

[[issues]]
  filepath = "api/http.go"
  fileline = 77

[[issues]]
  filepath = "api/http.go"
  fileline = 77

[[issues]]
  filepath = "control/job/job.go"
  fileline = 23

[[issues]]
  filepath = "api/grpc.go"
  fileline = 47

[[issues]]
  filepath = "api/grpc.go"
  fileline = 47
