repo = "github.com/micro/go-micro"
rule = "codelingo/go/shadowed-variable"
sha = "03031a694da1b256d0d7f2afb1a2926954c63c85"

[[issues]]
  filepath = "store/etcd/etcd.go"
  fileline = 239
  comment = "Variable keys shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "sync/task/broker/broker.go"
  fileline = 122
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "sync/task/broker/broker.go"
  fileline = 51
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "network/default.go"
  fileline = 457
  comment = "Variable records shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/memory/util.go"
  fileline = 71
  comment = "Variable metadata shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/memory/util.go"
  fileline = 55
  comment = "Variable metadata shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/cloudevents/cloudevents.go"
  fileline = 48
  comment = "Variable action shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/cloudevents/cloudevents.go"
  fileline = 47
  comment = "Variable topic shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tunnel/default.go"
  fileline = 1328
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tunnel/default.go"
  fileline = 1286
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tunnel/default.go"
  fileline = 1282
  comment = "Variable d shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/memory/memory_test.go"
  fileline = 82
  comment = "Variable services shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/memory/memory_test.go"
  fileline = 114
  comment = "Variable services shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/memory/memory_test.go"
  fileline = 157
  comment = "Variable services shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/resolver/micro/route.go"
  fileline = 30
  comment = "Variable name shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/resolver/micro/route.go"
  fileline = 37
  comment = "Variable name shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client/grpc/grpc_test.go"
  fileline = 80
  comment = "Variable rsp shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client/grpc/grpc_test.go"
  fileline = 76
  comment = "Variable req shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "util/grpc/grpc.go"
  fileline = 23
  comment = "Variable parts shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "server/grpc/grpc_test.go"
  fileline = 156
  comment = "Variable rsp shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "config/loader/memory/memory.go"
  fileline = 176
  comment = "Variable snap shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "router/default.go"
  fileline = 604
  comment = "Variable advertChan shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "broker/default.go"
  fileline = 239
  comment = "Variable port shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/http/http.go"
  fileline = 57
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "server/grpc/server.go"
  fileline = 183
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "server/grpc/server.go"
  fileline = 162
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/etcd/etcd.go"
  fileline = 153
  comment = "Variable ctx shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/etcd/etcd.go"
  fileline = 153
  comment = "Variable cancel shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/etcd/etcd.go"
  fileline = 174
  comment = "Variable h shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/web/web.go"
  fileline = 63
  comment = "Variable s shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "proxy/mucp/mucp.go"
  fileline = 541
  comment = "Variable body shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "proxy/mucp/mucp.go"
  fileline = 190
  comment = "Variable routes shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "registry/cache/cache.go"
  fileline = 134
  comment = "Variable services shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "util/ring/buffer_test.go"
  fileline = 40
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/event/event.go"
  fileline = 54
  comment = "Variable action shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "api/handler/event/event.go"
  fileline = 53
  comment = "Variable topic shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "monitor/default.go"
  fileline = 209
  comment = "Variable services shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "server/rpc_router.go"
  fileline = 222
  comment = "Variable fn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "broker/service/service.go"
  fileline = 103
  comment = "Variable stream shadows a variable of the same name declared in an outer scope."
