repo = "github.com/uber-go/zap"
rule = "codelingo/go/reassigned-error"
sha = "ec2dc456c680236892af2c645172713e1c4e1acd"

[[issues]]
  filepath = "zapcore/core_test.go"
  fileline = 71
  comment = "Error was not checked before reassignment"

[[issues]]
  filepath = "stacktrace_ext_test.go"
  fileline = 96
  comment = "Error was not checked before reassignment"
