repo = "rfjakob/gocryptfs"
rule = "unchecked-type-assertion"

[[issues]]
  filepath = "internal/cryptocore/cryptocore.go"
  fileline = 163
  fixed = false
  ignored = ""

[[issues]]
  filepath = "tests/test_helpers/helpers.go"
  fileline = 239
  fixed = false
  ignored = ""

[[issues]]
  filepath = "tests/reverse/correctness_test.go"
  fileline = 209
  fixed = false
  ignored = ""

[[issues]]
  filepath = "internal/fusefrontend_reverse/rfile.go"
  fileline = 78
  fixed = false
  ignored = ""

[[issues]]
  filepath = "internal/fusefrontend_reverse/rfile.go"
  fileline = 89
  fixed = false
  ignored = ""

[[issues]]
  filepath = "fsck.go"
  fileline = 182
  fixed = false
  ignored = ""

[[issues]]
  filepath = "fsck.go"
  fileline = 236
  fixed = false
  ignored = ""

[[issues]]
  filepath = "tests/test_helpers/helpers.go"
  fileline = 82
  fixed = false
  ignored = ""

[[issues]]
  filepath = "tests/xattr/xattr_integration_test.go"
  fileline = 219
  fixed = false
  ignored = ""

[[issues]]
  filepath = "internal/contentenc/bpool.go"
  fileline = 34
  fixed = false
  ignored = ""

[[issues]]
  filepath = "mount.go"
  fileline = 165
  fixed = false
  ignored = ""
