repo = "github.com/gorilla/mux"
rule = "codelingo/go/shadowed-variable"
sha = "75dcda0896e109a2a22c9315bca3bb21b87b2ba5"

[[issues]]
  filepath = "old_test.go"
  fileline = 507
  comment = "Variable url shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "regexp.go"
  fileline = 75
  comment = "Variable raw shadows a variable of the same name declared in an outer scope."
