repo = "github.com/txthinking/brook"
rule = "codelingo/go/shadowed-variable"
sha = "558f3261b51f0e9933ef8ec156cbd680e3416903"

[[issues]]
  filepath = "sysproxy/system_windows.go"
  fileline = 192
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "plugin/middleman/countryonly/countryonly.go"
  fileline = 183
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "plugin/middleman/countryonly/countryonly.go"
  fileline = 188
  comment = "Variable co shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "socks5.go"
  fileline = 197
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "socks5.go"
  fileline = 234
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "socks5.go"
  fileline = 248
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "socks5.go"
  fileline = 260
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "socks5.go"
  fileline = 224
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "plugin/middleman/blackwhite/blackwhite.go"
  fileline = 195
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "plugin/middleman/blackwhite/blackwhite.go"
  fileline = 200
  comment = "Variable co shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "dns.go"
  fileline = 229
  comment = "Variable k shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "dns.go"
  fileline = 225
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 451
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 436
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 495
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 423
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 373
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 397
  comment = "Variable cd shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 463
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 480
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 584
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 664
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 692
  comment = "Variable k shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "wsclient.go"
  fileline = 688
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 482
  comment = "Variable k shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 478
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 454
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 376
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 286
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 272
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 298
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "client.go"
  fileline = 231
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "ssclient.go"
  fileline = 260
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "ssclient.go"
  fileline = 248
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "ssclient.go"
  fileline = 234
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "ssclient.go"
  fileline = 203
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tunnel.go"
  fileline = 208
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tunnel.go"
  fileline = 212
  comment = "Variable k shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "server.go"
  fileline = 341
  comment = "Variable a shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tproxy_linux.go"
  fileline = 341
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "tproxy_linux.go"
  fileline = 345
  comment = "Variable k shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "ssserver.go"
  fileline = 306
  comment = "Variable a shadows a variable of the same name declared in an outer scope."
