repo = "github.com/kataras/iris"
rule = "codelingo/go/shadowed-variable"
sha = "3db1c90fc3d485ab30651ca50dc511203f276c7e"

[[issues]]
  filepath = "typescript/typescript.go"
  fileline = 125
  comment = "Variable absPath shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "context/gzip_response_writer.go"
  fileline = 30
  comment = "Variable gzipWriter shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "context/context.go"
  fileline = 3388
  comment = "Variable result shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "context/context.go"
  fileline = 3291
  comment = "Variable result shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "core/memstore/memstore.go"
  fileline = 728
  comment = "Variable kv shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "core/memstore/memstore.go"
  fileline = 706
  comment = "Variable kv shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "macro/interpreter/lexer/lexer.go"
  fileline = 90
  comment = "Variable typ shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "core/errgroup/errgroup.go"
  fileline = 120
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "core/errgroup/errgroup.go"
  fileline = 139
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "_examples/tutorial/online-visitors/main.go"
  fileline = 92
  comment = "Variable kv shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "_examples/tutorial/online-visitors/main.go"
  fileline = 82
  comment = "Variable kv shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "hero/handler.go"
  fileline = 53
  comment = "Variable h shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "mvc/controller_method_parser.go"
  fileline = 151
  comment = "Variable w shadows a variable of the same name declared in an outer scope."
