repo = "github.com/morya/bigotim"
rule = "default-in-type-switch"
sha = "de72eda6f7ff4ea04eda3060a0a2ca73597ca313"

[[issues]]
  filepath = "cmd/server/coder.go"
  fileline = 18

[[issues]]
  filepath = "cmd/client/coder.go"
  fileline = 23
