repo = "github.com/chai2010/advanced-go-programming-book"
rule = "codelingo/go/shadowed-variable"
sha = "73da73e5851b22b50540b59631570b65043b552d"

[[issues]]
  filepath = "examples/ch3.x/add/add_test.go"
  fileline = 91
  comment = "Variable dst shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "examples/ch3.x/add/add_test.go"
  fileline = 84
  comment = "Variable dst shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "examples/ch3.x/add/add_test.go"
  fileline = 77
  comment = "Variable dst shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "examples/ch3.x/add/add_test.go"
  fileline = 71
  comment = "Variable dst shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "examples/ch4.4/2/client/main.go"
  fileline = 45
  comment = "Variable reply shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "examples/ch4.4/basic/client/main.go"
  fileline = 90
  comment = "Variable reply shadows a variable of the same name declared in an outer scope."
