repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "094b3fdb393ff8eab16ec293bf49513213955523"

[[issues]]
  filepath = "context_test.go"
  fileline = 1899

[[issues]]
  filepath = "context_test.go"
  fileline = 1899

[[issues]]
  filepath = "context_test.go"
  fileline = 1900

[[issues]]
  filepath = "context_test.go"
  fileline = 1900

[[issues]]
  filepath = "context_test.go"
  fileline = 1900

[[issues]]
  filepath = "context_test.go"
  fileline = 1899

[[issues]]
  filepath = "context_test.go"
  fileline = 1900

[[issues]]
  filepath = "context_test.go"
  fileline = 1897

[[issues]]
  filepath = "context_test.go"
  fileline = 1899

[[issues]]
  filepath = "context_test.go"
  fileline = 1897

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 187

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 186

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 272

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 272

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 271

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 271

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 271

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 136

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 136

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 136

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 136

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 136

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 135

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 47

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 47

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 47

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 47

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 47

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 46

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 62

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 62

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 62

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 62

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 60

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 62

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 94

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 94

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 94

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 93

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 92

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 96

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 92

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 92

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 96

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 96

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 99

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 99

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 99

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 91

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 99

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 99

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 219

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 218

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 115

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 115

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 115

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 115

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 115

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 114

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 151

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 151

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 151

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 150

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 151

[[issues]]
  filepath = "gin_integration_test.go"
  fileline = 151

[[issues]]
  filepath = "debug_test.go"
  fileline = 131

[[issues]]
  filepath = "debug_test.go"
  fileline = 132

[[issues]]
  filepath = "debug_test.go"
  fileline = 129

[[issues]]
  filepath = "debug_test.go"
  fileline = 132

[[issues]]
  filepath = "debug_test.go"
  fileline = 129

[[issues]]
  filepath = "debug_test.go"
  fileline = 131

[[issues]]
  filepath = "debug_test.go"
  fileline = 130

[[issues]]
  filepath = "debug_test.go"
  fileline = 128

[[issues]]
  filepath = "debug_test.go"
  fileline = 130

[[issues]]
  filepath = "debug_test.go"
  fileline = 128

[[issues]]
  filepath = "debug_test.go"
  fileline = 131

[[issues]]
  filepath = "debug_test.go"
  fileline = 130
