repo = "github.com/nickysemenza/hyperion"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "1392edb4e04de42fd7988a6542db9b38092af3fa"

[[issues]]
  filepath = "api/http.go"
  fileline = 253

[[issues]]
  filepath = "api/http.go"
  fileline = 253

[[issues]]
  filepath = "api/http.go"
  fileline = 253

[[issues]]
  filepath = "api/http.go"
  fileline = 253

[[issues]]
  filepath = "api/http.go"
  fileline = 253

[[issues]]
  filepath = "api/http.go"
  fileline = 254

[[issues]]
  filepath = "api/http.go"
  fileline = 254

[[issues]]
  filepath = "api/http.go"
  fileline = 254

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 184

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 184

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 184

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 182

[[issues]]
  filepath = "api/http.go"
  fileline = 183

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "api/http.go"
  fileline = 181

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 92

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 94

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 92

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 93

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 94

[[issues]]
  filepath = "control/homekit/homekit.go"
  fileline = 93
