repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/unchecked-type-assertion"
sha = "094b3fdb393ff8eab16ec293bf49513213955523"

[[issues]]
  filepath = "utils_test.go"
  fileline = 114

[[issues]]
  filepath = "gin.go"
  fileline = 365
