repo = "github.com/v2ray/v2ray-core"
rule = "codelingo/go/unchecked-type-assertion"
sha = "c44dd395072f77e0e51a4258a159d2dbbc340371"

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "testing/servers/udp/port.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/client.go"
  fileline = 109
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 117
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 114
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/tcp/dialer.go"
  fileline = 32
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 203
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 182
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/listener.go"
  fileline = 39
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/server.go"
  fileline = 298
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "v2ray.go"
  fileline = 80
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/tcp/hub.go"
  fileline = 38
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 352
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/socks/protocol.go"
  fileline = 412
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "testing/servers/tcp/tcp.go"
  fileline = 41
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/validator.go"
  fileline = 81
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/headers/tls/dtls_test.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/http/client.go"
  fileline = 135
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/lucas-clemente/quic-go/internal/qerr/quic_error.go"
  fileline = 46
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/strmatcher/strmatcher.go"
  fileline = 74
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/domainsocket/listener.go"
  fileline = 30
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "v2ray.go"
  fileline = 98
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/tls.go"
  fileline = 252
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 198
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/segment_test.go"
  fileline = 59
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/server.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/conn.go"
  fileline = 1317
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/dns/dns_test.go"
  fileline = 40
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/handshake_server.go"
  fileline = 843
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/serial/string.go"
  fileline = 14
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/http/hub.go"
  fileline = 98
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "testing/servers/udp/udp.go"
  fileline = 30
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/conn.go"
  fileline = 485
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "infra/conf/serial/loader.go"
  fileline = 53
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/headers/utp/utp_test.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/lucas-clemente/quic-go/buffer_pool.go"
  fileline = 47
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/sending.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/proxyman/inbound/always.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/headers/wechat/wechat_test.go"
  fileline = 16
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/serial/typed_message.go"
  fileline = 42
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/sending.go"
  fileline = 61
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/websocket/dialer.go"
  fileline = 33
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/conn.go"
  fileline = 989
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/http/dialer.go"
  fileline = 72
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/quic/dialer.go"
  fileline = 211
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/outbound/outbound.go"
  fileline = 101
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/udp/hub.go"
  fileline = 58
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/lucas-clemente/quic-go/session.go"
  fileline = 578
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/server.go"
  fileline = 138
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 415
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/inbound/inbound.go"
  fileline = 338
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/errors/errors.go"
  fileline = 166
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/quic/hub.go"
  fileline = 95
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 520
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/sending.go"
  fileline = 283
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/receiving.go"
  fileline = 241
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/client.go"
  fileline = 206
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/stats/stats_test.go"
  fileline = 20
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/connection.go"
  fileline = 569
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/domainsocket/dial.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 229
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/tls.go"
  fileline = 284
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/proxyman/inbound/always.go"
  fileline = 25
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 38
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "v2ray.go"
  fileline = 124
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/log/log.go"
  fileline = 103
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/headers/srtp/srtp_test.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/segment_test.go"
  fileline = 82
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/dialer.go"
  fileline = 60
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/websocket/hub.go"
  fileline = 61
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/conn.go"
  fileline = 355
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/net/address.go"
  fileline = 184
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/outbound/command.go"
  fileline = 36
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 288
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/proxyman/inbound/always.go"
  fileline = 23
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/common.go"
  fileline = 1062
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/proxyman/outbound/handler.go"
  fileline = 43
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/proxyman/inbound/dynamic.go"
  fileline = 123
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "testing/servers/tcp/port.go"
  fileline = 14
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/server.go"
  fileline = 219
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 168
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/dns/server_test.go"
  fileline = 351
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/sending.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/vmess/encoding/client.go"
  fileline = 60
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "common/net/destination.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/segment_test.go"
  fileline = 36
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/marten-seemann/qtls/common.go"
  fileline = 1049
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/sending.go"
  fileline = 142
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "proxy/shadowsocks/protocol.go"
  fileline = 167
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "external/github.com/lucas-clemente/quic-go/internal/wire/log.go"
  fileline = 20
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "app/router/condition.go"
  fileline = 314
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "transport/internet/kcp/segment_test.go"
  fileline = 103
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
