repo = "github.com/buger/goreplay"
rule = "codelingo/go/pointer-leaves-method"
sha = "ffc1a09ca1e465dc1b67efc151dab2771e1086c7"

[[issues]]
  filepath = "vendor/github.com/Shopify/sarama/consumer.go"
  fileline = 135
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "vendor/github.com/Shopify/sarama/offset_manager.go"
  fileline = 393
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "vendor/github.com/Shopify/sarama/consumer.go"
  fileline = 559
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "vendor/github.com/Shopify/sarama/offset_manager.go"
  fileline = 193
  comment = "The receiver pointer is returned from this method. Make a copy instead."
