repo = "github.com/caddyserver/caddy"
rule = "codelingo/go/ticker-in-for-select"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  comment = "Make one ticker as opposed to making a new timer each iteration."
  fileline = 75
  filepath = "caddytls/crypto_test.go"
  fixed = true
  ignored = ""
