repo = "github.com/joewalnes/websocketd"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "7c9231ab6342ce6e9ede8af036cd2e940c2598c5"

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 34
  comment = "The variable pe should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 34
  comment = "The variable cmd should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 34
  comment = "The variable process should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 34
  comment = "The variable Wait should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/process_endpoint.go"
  fileline = 34
  comment = "The variable terminated should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 100
  comment = "The variable config should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 105
  comment = "The variable Redirect should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 105
  comment = "The variable StatusMovedPermanently should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 100
  comment = "The variable Ssl should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 103
  comment = "The variable pos should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 105
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 103
  comment = "The variable strings should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 103
  comment = "The variable Host should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 103
  comment = "The variable Host should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 103
  comment = "The variable IndexByte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 105
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 94
  comment = "The variable IndexByte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 107
  comment = "The variable Info should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 108
  comment = "The variable rejects should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable ResponseWriter should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 95
  comment = "The variable RedirPort should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 108
  comment = "The variable ListenAndServe should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable HandlerFunc should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 95
  comment = "The variable config should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable Handler should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 95
  comment = "The variable Itoa should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable Addr should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 94
  comment = "The variable strings should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable Server should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 107
  comment = "The variable log should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 96
  comment = "The variable Request should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 95
  comment = "The variable strconv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 44
  comment = "The variable limit should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 44
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 47
  comment = "The variable Sleep should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 48
  comment = "The variable close should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 48
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 47
  comment = "The variable time should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 47
  comment = "The variable Millisecond should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 47
  comment = "The variable time should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 48
  comment = "The variable c should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable byte should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable strconv should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable c should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable prefix should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable e should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable i should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "libwebsocketd/endpoint_test.go"
  fileline = 45
  comment = "The variable Itoa should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable CertFile should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable KeyFile should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable config should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable rejects should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable config should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 86
  comment = "The variable ListenAndServeTLS should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 88
  comment = "The variable ListenAndServe should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 88
  comment = "The variable nil should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 88
  comment = "The variable http should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 88
  comment = "The variable rejects should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 85
  comment = "The variable Ssl should be passed in as arguments to go-routines to avoid race conditions."

[[issues]]
  filepath = "main.go"
  fileline = 85
  comment = "The variable config should be passed in as arguments to go-routines to avoid race conditions."
