repo = "github.com/sundy-li/go_commons"
rule = "codelingo/go/default-in-type-switch"
sha = "84e4cb0afce4401a08fab57d23876b840ae4c979"

[[issues]]
  fileline = 87
  filepath = "libs/gomysql/gomysql.go"
  fixed = true
  ignored = ""

[[issues]]
  fileline = 41
  filepath = "libs/gomysql/gomysql.go"
  fixed = true
  ignored = ""
