repo = "github.com/urfave/cli"
rule = "codelingo/go/shadowed-variable"
sha = "120c9eead1a53482088819c06c6251010f82c0a0"

[[issues]]
  filepath = "altsrc/map_input_source.go"
  fileline = 157
  comment = "Variable isType shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "altsrc/map_input_source.go"
  fileline = 186
  comment = "Variable isType shadows a variable of the same name declared in an outer scope."
