repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/default-in-type-switch"
sha = "094b3fdb393ff8eab16ec293bf49513213955523"

[[issues]]
  fileline = 36
  filepath = "binding/multipart_form_mapping.go"
  fixed = false
  ignored = "error returned if no cases match"

[[issues]]
  fileline = 208
  filepath = "binding/form_mapping.go"
  fixed = false
  ignored = "handled by fallthrough"

[[issues]]
  fileline = 30
  filepath = "binding/multipart_form_mapping.go"
  fixed = false
  ignored = "handled by fallthrough"

[[issues]]
  fileline = 184
  filepath = "binding/form_mapping.go"
  fixed = false
  ignored = "handled by fallthrough"
