repo = "github.com/gin-gonic/gin"
rule = "codelingo/go/default-in-type-switch"
sha = "a71af9c144f9579f6dbe945341c1df37aaf09c0d"

[[issues]]
  filepath = "binding/form_mapping.go"
  fileline = 208
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "binding/multipart_form_mapping.go"
  fileline = 30
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "binding/form_mapping.go"
  fileline = 184
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "binding/multipart_form_mapping.go"
  fileline = 36
  comment = "Always include a default case when using a type switch."
