repo = "github.com/gadelkareem/cachita"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "27c05434ad48d5cbb92e0af613152ed5ac17dbe5"

[[issues]]
  filepath = "cache.go"
  fileline = 60

[[issues]]
  filepath = "cache.go"
  fileline = 60

[[issues]]
  filepath = "cache.go"
  fileline = 61
