repo = "github.com/BeFunes/go-test"
rule = "codelingo/go/shadowed-variable"
sha = "f0b6715757838d21fe9a88b7e8103531e15c23cb"

[[issues]]
  fileline = 72
  filepath = "_examples/encoding/easyjson.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 192
  filepath = "_examples/instrumentation/apmelasticsearch.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 158
  filepath = "_examples/instrumentation/apmelasticsearch.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 116
  filepath = "_examples/instrumentation/apmelasticsearch.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 231
  filepath = "_examples/instrumentation/apmelasticsearch.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 82
  filepath = "_examples/main.go"
  fixed = false
  ignored = "fp"

[[issues]]
  fileline = 278
  filepath = "internal/cmd/generate/commands/gentests/command.go"
  fixed = false
  ignored = "fp"
