repo = "github.com/SimonWaldherr/golibs"
rule = "default-in-type-switch"
sha = "d8150802aaa814bf0cba43fa97d6db29ff67c8a6"

[[issues]]
  fileline = 81
  filepath = "foreach/foreach_test.go"
  fixed = false
  ignored = "in simple test"

[[issues]]
  fileline = 37
  filepath = "node/node_test.go"
  fixed = false
  ignored = "in simple test"
