repo = "github.com/arthurkiller/perfm"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "faffaaaf27828a68bc8ea45cf117f6c711f53620"

[[issues]]
  filepath = "perfm.go"
  fileline = 223

[[issues]]
  filepath = "perfm.go"
  fileline = 224

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 226

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 226

[[issues]]
  filepath = "perfm.go"
  fileline = 224

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 226

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 225

[[issues]]
  filepath = "perfm.go"
  fileline = 223

[[issues]]
  filepath = "perfm.go"
  fileline = 223

[[issues]]
  filepath = "perfm.go"
  fileline = 120

[[issues]]
  filepath = "perfm.go"
  fileline = 138

[[issues]]
  filepath = "perfm.go"
  fileline = 139

[[issues]]
  filepath = "perfm.go"
  fileline = 128

[[issues]]
  filepath = "perfm.go"
  fileline = 134

[[issues]]
  filepath = "perfm.go"
  fileline = 129

[[issues]]
  filepath = "perfm.go"
  fileline = 138

[[issues]]
  filepath = "perfm.go"
  fileline = 128

[[issues]]
  filepath = "perfm.go"
  fileline = 125

[[issues]]
  filepath = "perfm.go"
  fileline = 127

[[issues]]
  filepath = "perfm.go"
  fileline = 125

[[issues]]
  filepath = "perfm.go"
  fileline = 134

[[issues]]
  filepath = "perfm.go"
  fileline = 117

[[issues]]
  filepath = "perfm.go"
  fileline = 120

[[issues]]
  filepath = "perfm.go"
  fileline = 112

[[issues]]
  filepath = "perfm.go"
  fileline = 124

[[issues]]
  filepath = "perfm.go"
  fileline = 138

[[issues]]
  filepath = "perfm.go"
  fileline = 117

[[issues]]
  filepath = "perfm.go"
  fileline = 127

[[issues]]
  filepath = "perfm.go"
  fileline = 124

[[issues]]
  filepath = "perfm.go"
  fileline = 115

[[issues]]
  filepath = "perfm.go"
  fileline = 129

[[issues]]
  filepath = "perfm.go"
  fileline = 113

[[issues]]
  filepath = "perfm.go"
  fileline = 126

[[issues]]
  filepath = "perfm.go"
  fileline = 139

[[issues]]
  filepath = "perfm.go"
  fileline = 114

[[issues]]
  filepath = "perfm.go"
  fileline = 126

[[issues]]
  filepath = "perfm.go"
  fileline = 116

[[issues]]
  filepath = "perfm.go"
  fileline = 115

[[issues]]
  filepath = "perfm.go"
  fileline = 128

[[issues]]
  filepath = "perfm.go"
  fileline = 139

[[issues]]
  filepath = "perfm.go"
  fileline = 113

[[issues]]
  filepath = "perfm.go"
  fileline = 114

[[issues]]
  filepath = "perfm.go"
  fileline = 115

[[issues]]
  filepath = "perfm.go"
  fileline = 112

[[issues]]
  filepath = "perfm.go"
  fileline = 116

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 135

[[issues]]
  filepath = "perfm.go"
  fileline = 135

[[issues]]
  filepath = "perfm.go"
  fileline = 135

[[issues]]
  filepath = "perfm.go"
  fileline = 135

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 135

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 136

[[issues]]
  filepath = "perfm.go"
  fileline = 131

[[issues]]
  filepath = "perfm.go"
  fileline = 132

[[issues]]
  filepath = "perfm.go"
  fileline = 130

[[issues]]
  filepath = "perfm.go"
  fileline = 131

[[issues]]
  filepath = "perfm.go"
  fileline = 130

[[issues]]
  filepath = "perfm.go"
  fileline = 132

[[issues]]
  filepath = "perfm.go"
  fileline = 132

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 121

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 121

[[issues]]
  filepath = "perfm.go"
  fileline = 121

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 121

[[issues]]
  filepath = "perfm.go"
  fileline = 122

[[issues]]
  filepath = "perfm.go"
  fileline = 121

[[issues]]
  filepath = "perfm.go"
  fileline = 109

[[issues]]
  filepath = "perfm.go"
  fileline = 108

[[issues]]
  filepath = "perfm.go"
  fileline = 108

[[issues]]
  filepath = "perfm.go"
  fileline = 109

[[issues]]
  filepath = "perfm.go"
  fileline = 108

[[issues]]
  filepath = "perfm.go"
  fileline = 108

[[issues]]
  filepath = "perfm.go"
  fileline = 158

[[issues]]
  filepath = "perfm.go"
  fileline = 151

[[issues]]
  filepath = "perfm.go"
  fileline = 159

[[issues]]
  filepath = "perfm.go"
  fileline = 153

[[issues]]
  filepath = "perfm.go"
  fileline = 153

[[issues]]
  filepath = "perfm.go"
  fileline = 152

[[issues]]
  filepath = "perfm.go"
  fileline = 154

[[issues]]
  filepath = "perfm.go"
  fileline = 159

[[issues]]
  filepath = "perfm.go"
  fileline = 160

[[issues]]
  filepath = "perfm.go"
  fileline = 151

[[issues]]
  filepath = "perfm.go"
  fileline = 165

[[issues]]
  filepath = "perfm.go"
  fileline = 165

[[issues]]
  filepath = "perfm.go"
  fileline = 165

[[issues]]
  filepath = "perfm.go"
  fileline = 164

[[issues]]
  filepath = "perfm.go"
  fileline = 170

[[issues]]
  filepath = "perfm.go"
  fileline = 170

[[issues]]
  filepath = "perfm.go"
  fileline = 155

[[issues]]
  filepath = "perfm.go"
  fileline = 155

[[issues]]
  filepath = "perfm.go"
  fileline = 177

[[issues]]
  filepath = "perfm.go"
  fileline = 177

[[issues]]
  filepath = "perfm.go"
  fileline = 177

[[issues]]
  filepath = "perfm.go"
  fileline = 177

[[issues]]
  filepath = "perfm.go"
  fileline = 163

[[issues]]
  filepath = "perfm.go"
  fileline = 173

[[issues]]
  filepath = "perfm.go"
  fileline = 174

[[issues]]
  filepath = "perfm.go"
  fileline = 173

[[issues]]
  filepath = "perfm.go"
  fileline = 163

[[issues]]
  filepath = "perfm.go"
  fileline = 169

[[issues]]
  filepath = "perfm.go"
  fileline = 163

[[issues]]
  filepath = "perfm.go"
  fileline = 174

[[issues]]
  filepath = "perfm.go"
  fileline = 163

[[issues]]
  filepath = "perfm.go"
  fileline = 163

[[issues]]
  filepath = "perfm.go"
  fileline = 169

[[issues]]
  filepath = "perfm.go"
  fileline = 169

[[issues]]
  filepath = "perfm.go"
  fileline = 175

[[issues]]
  filepath = "perfm.go"
  fileline = 176

[[issues]]
  filepath = "perfm.go"
  fileline = 175

[[issues]]
  filepath = "perfm.go"
  fileline = 175

[[issues]]
  filepath = "perfm.go"
  fileline = 175

[[issues]]
  filepath = "perfm.go"
  fileline = 205

[[issues]]
  filepath = "perfm.go"
  fileline = 205

[[issues]]
  filepath = "perfm.go"
  fileline = 212

[[issues]]
  filepath = "perfm.go"
  fileline = 212

[[issues]]
  filepath = "perfm.go"
  fileline = 212

[[issues]]
  filepath = "perfm.go"
  fileline = 212

[[issues]]
  filepath = "perfm.go"
  fileline = 190

[[issues]]
  filepath = "perfm.go"
  fileline = 191

[[issues]]
  filepath = "perfm.go"
  fileline = 191

[[issues]]
  filepath = "perfm.go"
  fileline = 197

[[issues]]
  filepath = "perfm.go"
  fileline = 189

[[issues]]
  filepath = "perfm.go"
  fileline = 192

[[issues]]
  filepath = "perfm.go"
  fileline = 198

[[issues]]
  filepath = "perfm.go"
  fileline = 196

[[issues]]
  filepath = "perfm.go"
  fileline = 197

[[issues]]
  filepath = "perfm.go"
  fileline = 189

[[issues]]
  filepath = "perfm.go"
  fileline = 214

[[issues]]
  filepath = "perfm.go"
  fileline = 210

[[issues]]
  filepath = "perfm.go"
  fileline = 204

[[issues]]
  filepath = "perfm.go"
  fileline = 209

[[issues]]
  filepath = "perfm.go"
  fileline = 201

[[issues]]
  filepath = "perfm.go"
  fileline = 211

[[issues]]
  filepath = "perfm.go"
  fileline = 204

[[issues]]
  filepath = "perfm.go"
  fileline = 210

[[issues]]
  filepath = "perfm.go"
  fileline = 201

[[issues]]
  filepath = "perfm.go"
  fileline = 204

[[issues]]
  filepath = "perfm.go"
  fileline = 214

[[issues]]
  filepath = "perfm.go"
  fileline = 208

[[issues]]
  filepath = "perfm.go"
  fileline = 210

[[issues]]
  filepath = "perfm.go"
  fileline = 209

[[issues]]
  filepath = "perfm.go"
  fileline = 214

[[issues]]
  filepath = "perfm.go"
  fileline = 214

[[issues]]
  filepath = "perfm.go"
  fileline = 210

[[issues]]
  filepath = "perfm.go"
  fileline = 208

[[issues]]
  filepath = "perfm.go"
  fileline = 193

[[issues]]
  filepath = "perfm.go"
  fileline = 193
