repo = "github.com/caddyserver/caddy"
rule = "codelingo/go/default-in-type-switch"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  filepath = "caddyfile/json.go"
  fileline = 138
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "caddyhttp/gzip/setup_test.go"
  fileline = 127
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "telemetry/telemetry.go"
  fileline = 328
  comment = "Always include a default case when using a type switch."
