repo = "github.com/iawia002/annie"
rule = "codelingo/go/insecure-http-connection"
sha = "c24fbc04b8260cc5923af12be9baf30d35735325"

[[issues]]
  filepath = "request/request.go"
  fileline = 31
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
