repo = "github.com/containous/traefik"
rule = "codelingo/lomik-go-carbon/missing-stop-ticker"
sha = "16c48071621ac2f38bd02d55854574f384c913f0"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 75
  filepath = "pkg/metrics/datadog.go"
  fixed = false
  ignored = "ticker returned from func"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 81
  filepath = "pkg/metrics/statsd.go"
  fixed = false
  ignored = "fp. ticker returned from func"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 128
  filepath = "pkg/metrics/influxdb.go"
  fixed = false
  ignored = "ticker returned from func"

[[issues]]
  comment = "Stop the ticker to release associated resources."
  fileline = 20
  filepath = "pkg/metrics/metrics_test.go"
  fixed = true
  ignored = ""
