repo = "github.com/bilibili/kratos"
rule = "codelingo/go/unchecked-type-assertion"
sha = "8de8758d3d5f40ea047de945c5969fab59a2acda"

[[issues]]
  filepath = "pkg/conf/paladin/toml.go"
  fileline = 62
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/metadata/metadata.go"
  fileline = 58
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 185
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "tool/pkg/common.go"
  fileline = 62
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/memcache/encoding.go"
  fileline = 154
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 237
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 74
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 197
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 22
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 17
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 180
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 208
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 286
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 173
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/conf/dsn/query.go"
  fileline = 112
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 180
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/marshal_test.go"
  fileline = 10
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 129
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list.go"
  fileline = 127
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/log.go"
  fileline = 49
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/internal/core/pool.go"
  fileline = 44
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 84
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/pattern.go"
  fileline = 82
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/p2c/p2c_test.go"
  fileline = 176
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/conf/paladin/toml.go"
  fileline = 59
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 90
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/conn.go"
  fileline = 336
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 90
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 57
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 256
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 199
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "tool/protobuf/pkg/generator/http.go"
  fileline = 120
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/pattern.go"
  fileline = 67
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 62
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 76
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/wrr/wrr_test.go"
  fileline = 110
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/internal/filewriter/filewriter.go"
  fileline = 286
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/wrr/wrr_test.go"
  fileline = 96
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/memcache/encoding.go"
  fileline = 151
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/p2c/p2c_test.go"
  fileline = 336
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 105
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/internal/status/status.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "tool/protobuf/pkg/generator/http.go"
  fileline = 117
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/internal/filewriter/filewriter_test.go"
  fileline = 52
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/marshal.go"
  fileline = 57
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/p2c/p2c_test.go"
  fileline = 274
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/conf/paladin/toml.go"
  fileline = 65
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 220
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/conf/paladin/map.go"
  fileline = 29
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/report_test.go"
  fileline = 80
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 99
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/p2c/p2c_test.go"
  fileline = 189
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/pubsub_test.go"
  fileline = 53
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 85
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 86
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 114
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/wrr/wrr_test.go"
  fileline = 85
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/dapper.go"
  fileline = 183
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 169
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 42
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 111
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/pool_test.go"
  fileline = 61
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/conf/paladin/toml.go"
  fileline = 56
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 148
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/wrr/wrr_test.go"
  fileline = 73
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 232
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 90
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 248
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 201
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/slice_test.go"
  fileline = 121
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 49
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 191
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list_test.go"
  fileline = 169
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/span_test.go"
  fileline = 21
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 206
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/ratelimit/bbr/bbr_test.go"
  fileline = 131
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/container/pool/list.go"
  fileline = 97
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 71
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 198
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/balancer/p2c/p2c_test.go"
  fileline = 164
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/time/time.go"
  fileline = 15
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/internal/filewriter/filewriter.go"
  fileline = 164
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/trace/report_test.go"
  fileline = 42
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/log/internal/core/field.go"
  fileline = 67
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 144
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/net/rpc/warden/server_test.go"
  fileline = 463
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 154
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/reply.go"
  fileline = 40
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/cache/redis/scan.go"
  fileline = 117
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "pkg/str/str.go"
  fileline = 26
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
