repo = "github.com/Masterminds/glide"
rule = "codelingo/go/shadowed-variable"
sha = "b94b39d657d8abcccba6545e148f1201aee6ffec"

[[issues]]
  filepath = "vendor/github.com/codegangsta/cli/altsrc/map_input_source.go"
  fileline = 147
  comment = "Variable isType shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/codegangsta/cli/altsrc/map_input_source.go"
  fileline = 176
  comment = "Variable isType shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/vcs/svn.go"
  fileline = 279
  comment = "Variable out shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "action/config_wizard.go"
  fileline = 29
  comment = "Variable conf shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/scannerc.go"
  fileline = 1281
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "repo/vcs.go"
  fileline = 168
  comment = "Variable repo shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/mitchellh/go-homedir/homedir_test.go"
  fileline = 91
  comment = "Variable actual shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 906
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 581
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 677
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 772
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/gopkg.in/yaml.v2/parserc.go"
  fileline = 861
  comment = "Variable token shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 365
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 377
  comment = "Variable msgs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 371
  comment = "Variable v shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 459
  comment = "Variable msgs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 460
  comment = "Variable e shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 447
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "vendor/github.com/Masterminds/semver/constraints_test.go"
  fileline = 453
  comment = "Variable v shadows a variable of the same name declared in an outer scope."
