repo = "github.com/gadelkareem/cachita"
rule = "codelingo/lomik-go-carbon/missing-stop-ticker"
sha = "27c05434ad48d5cbb92e0af613152ed5ac17dbe5"

[[issues]]
  fileline = 56
  filepath = "cache.go"
  fixed = false
  ignored = "never finishes"
