repo = "github.com/grpc-ecosystem/grpc-gateway"
rule = "codelingo/go/unchecked-type-assertion"
sha = "da18680cd10b7acf76a7175b2b0523fda9fa188c"

[[issues]]
  filepath = "examples/internal/proto/examplepb/response_body_service.pb.gw.go"
  fileline = 388
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "examples/internal/proto/examplepb/response_body_service.pb.gw.go"
  fileline = 379
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "protoc-gen-swagger/genswagger/template_test.go"
  fileline = 1277
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "examples/internal/proto/examplepb/response_body_service.pb.gw.go"
  fileline = 370
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query_test.go"
  fileline = 751
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query_test.go"
  fileline = 794
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query_test.go"
  fileline = 753
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query_test.go"
  fileline = 796
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query.go"
  fileline = 221
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "protoc-gen-swagger/genswagger/template_test.go"
  fileline = 1285
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query.go"
  fileline = 319
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "runtime/query_test.go"
  fileline = 772
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
