repo = "github.com/gadelkareem/flatten-arr"
rule = "codelingo/go/default-in-type-switch"
sha = "9332e1cd106659ea77f28a4bc417ba96c0a4e7b7"

[[issues]]
  fileline = 13
  filepath = "src/flatten-arr/main.go"
  fixed = false
  ignored = "catch-all case present"
