repo = "github.com/ipfs/go-ipfs"
rule = "codelingo/go/pointer-leaves-method"
sha = "4acb15d52b26bc71071f44f71ef0a72b547cf855"

[[issues]]
  filepath = "p2p/remote.go"
  fileline = 33
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "p2p/local.go"
  fileline = 32
  comment = "The receiver pointer is returned from this method. Make a copy instead."
