repo = "github.com/friendlydan/dash-demo"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "6bad7b7ab520ce73c7868632d08994b8aec3260e"

[[issues]]
  filepath = "main.go"
  fileline = 31
  comment = "Close the file when you are done"

[[issues]]
  filepath = "main.go"
  fileline = 38
  comment = "Close the file when you are done"

[[issues]]
  filepath = "main.go"
  fileline = 15
  comment = "Close the file when you are done"

[[issues]]
  filepath = "main.go"
  fileline = 21
  comment = "Close the file when you are done"
