repo = "github.com/labstack/echo"
rule = "codelingo/go/shadowed-variable"
sha = "fc4b1c0a830f194bf6334d2b3e61d92cccebb2be"

[[issues]]
  filepath = "context_test.go"
  fileline = 250
  comment = "Variable assert shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "context_test.go"
  fileline = 232
  comment = "Variable assert shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "middleware/compress_test.go"
  fileline = 43
  comment = "Variable buf shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "bind_test.go"
  fileline = 416
  comment = "Variable val shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "router.go"
  fileline = 115
  comment = "Variable l shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "middleware/jwt_test.go"
  fileline = 43
  comment = "Variable c shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "echo.go"
  fileline = 615
  comment = "Variable h shadows a variable of the same name declared in an outer scope."
