repo = "github.com/containous/traefik"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "16c48071621ac2f38bd02d55854574f384c913f0"

[[issues]]
  filepath = "integration/log_rotation_test.go"
  fileline = 151
  comment = "Close the file when you are done"
