repo = "github.com/containous/traefik"
rule = "codelingo/go/shadowed-variable"
sha = "16c48071621ac2f38bd02d55854574f384c913f0"

[[issues]]
  filepath = "pkg/udp/conn_test.go"
  fileline = 164
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/udp/conn_test.go"
  fileline = 170
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/udp/conn_test.go"
  fileline = 35
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/udp/conn_test.go"
  fileline = 34
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/udp/proxy_test.go"
  fileline = 16
  comment = "Variable b shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/udp/proxy_test.go"
  fileline = 17
  comment = "Variable n shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "cmd/traefik/traefik.go"
  fileline = 215
  comment = "Variable ctx shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "integration/websocket_test.go"
  fileline = 303
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "integration/websocket_test.go"
  fileline = 397
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/server/router/tcp/router.go"
  fileline = 116
  comment = "Variable logger shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/server/router/tcp/router.go"
  fileline = 184
  comment = "Variable logger shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/server/service/loadbalancer/mirror/mirror.go"
  fileline = 185
  comment = "Variable body shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/tcp/proxy_test.go"
  fileline = 57
  comment = "Variable conn shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "integration/rest_test.go"
  fileline = 212
  comment = "Variable response shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "integration/rest_test.go"
  fileline = 209
  comment = "Variable request shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/provider/kubernetes/crd/generated/informers/externalversions/factory.go"
  fileline = 137
  comment = "Variable informers shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "pkg/provider/kubernetes/crd/kubernetes_http.go"
  fileline = 226
  comment = "Variable k8sService shadows a variable of the same name declared in an outer scope."
