repo = "github.com/morya/bigotim"
rule = "unchecked-type-assertion"
sha = "de72eda6f7ff4ea04eda3060a0a2ca73597ca313"

[[issues]]
  fileline = 18
  filepath = "cmd/server/coder.go"
  fixed = false
  ignored = "fp. assertion in switch stmt"

[[issues]]
  fileline = 23
  filepath = "cmd/client/coder.go"
  fixed = false
  ignored = "fp. assertion in switch stmt"
