repo = "github.com/grpc-ecosystem/grpc-gateway"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "da18680cd10b7acf76a7175b2b0523fda9fa188c"

[[issues]]
  filepath = "protoc-gen-swagger/main.go"
  fileline = 57
  comment = "Close the file when you are done"
