repo = "github.com/gadelkareem/cachita"
rule = "missing-stop-ticker"
sha = "27c05434ad48d5cbb92e0af613152ed5ac17dbe5"

[[issues]]
  fileline = 56
  filepath = "cache.go"
  fixed = false
  ignored = "goroutine never exits. runs for prog duration"
