repo = "github.com/kataras/iris"
rule = "codelingo/go/pointer-leaves-method"
sha = "3db1c90fc3d485ab30651ca50dc511203f276c7e"

[[issues]]
  filepath = "sessions/provider.go"
  fileline = 63
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "core/errgroup/errgroup.go"
  fileline = 260
  comment = "The receiver pointer is returned from this method. Make a copy instead."
