repo = "github.com/tonyalaribe/ninja"
rule = "codelingo/go/unchecked-type-assertion"
sha = "532184d51e030cc342861712fa10d58a4842b8fb"

[[issues]]
  filepath = "uilayer/rest/main_integration_test.go"
  fileline = 40
