repo = "github.com/HiepPP/golang-practice-basic"
rule = "codelingo/go/unsafe-go-routine-variables"
sha = "afba2478c6adaa3c1f49071e93d0b9147122dfc5"

[[issues]]
  filepath = "concurent/goroutine.go"
  fileline = 14

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 13

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 14

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 14

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 14

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 14

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 26

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 29

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 27

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 27

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 28

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 29

[[issues]]
  filepath = "concurent/goroutine1.go"
  fileline = 19

[[issues]]
  filepath = "concurent/goroutine1.go"
  fileline = 17

[[issues]]
  filepath = "concurent/goroutine1.go"
  fileline = 18

[[issues]]
  filepath = "concurent/goroutine1.go"
  fileline = 17

[[issues]]
  filepath = "concurent/goroutine1.go"
  fileline = 19

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 20

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 19

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 20

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 20

[[issues]]
  filepath = "concurent/chan.go"
  fileline = 20
