repo = "github.com/sundy-li/go_commons"
rule = "codelingo/go/ticker-in-for-select"
sha = "84e4cb0afce4401a08fab57d23876b840ae4c979"

[[issues]]
  fileline = 456
  filepath = "libs/kafka/reader.go"
  fixed = false
  ignored = ""

[[issues]]
  fileline = 625
  filepath = "libs/kafka/reader.go"
  fixed = false
  ignored = ""
