repo = "github.com/micro/go-micro"
rule = "codelingo/rfjakob-gocryptfs/missing-close-file"
sha = "03031a694da1b256d0d7f2afb1a2926954c63c85"

[[issues]]
  filepath = "runtime/local/build/docker/docker.go"
  fileline = 31
  comment = "Close the file when you are done"
