repo = "github.com/revel/revel"
rule = "codelingo/go/unchecked-type-assertion"
sha = "a3d7a7c23ca885cc5036d3641ede49ce4a14ee2e"

[[issues]]
  filepath = "template_functions.go"
  fileline = 181
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "before_after_filter.go"
  fileline = 28
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server-engine.go"
  fileline = 170
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 23
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "invoker_test.go"
  fileline = 75
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "binder_test.go"
  fileline = 204
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "results.go"
  fileline = 72
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "logger/terminal_format.go"
  fileline = 136
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 27
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "binder_test.go"
  fileline = 199
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template.go"
  fileline = 95
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 284
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "intercept.go"
  fileline = 121
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "before_after_filter.go"
  fileline = 24
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "router.go"
  fileline = 193
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template.go"
  fileline = 100
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 57
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "before_after_filter.go"
  fileline = 18
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "binder.go"
  fileline = 143
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template.go"
  fileline = 436
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server_adapter_go.go"
  fileline = 139
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "server_adapter_go.go"
  fileline = 382
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 178
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "invoker.go"
  fileline = 48
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "session/session.go"
  fileline = 234
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "logger/terminal_format.go"
  fileline = 171
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 189
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "validators.go"
  fileline = 230
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "before_after_filter.go"
  fileline = 12
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "logger/terminal_format.go"
  fileline = 108
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "http.go"
  fileline = 317
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 221
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 56
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 25
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "revel.go"
  fileline = 204
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "http.go"
  fileline = 86
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 281
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "template_functions.go"
  fileline = 300
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "utils/simplestack_test.go"
  fileline = 55
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "i18n.go"
  fileline = 93
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
