repo = "github.com/wtfutil/wtf"
rule = "codelingo/go/shadowed-variable"
sha = "e453408457d62934848146e61771cd96f78985ab"

[[issues]]
  filepath = "modules/gcal/cal_event.go"
  fileline = 102
  comment = "Variable startTime shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "utils/utils.go"
  fileline = 96
  comment = "Variable cmd shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "modules/gcal/display.go"
  fileline = 45
  comment = "Variable title shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "modules/pocket/widget.go"
  fileline = 142
  comment = "Variable content shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "modules/pocket/widget.go"
  fileline = 151
  comment = "Variable content shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "modules/pocket/widget.go"
  fileline = 154
  comment = "Variable content shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "modules/twitter/widget.go"
  fileline = 70
  comment = "Variable str shadows a variable of the same name declared in an outer scope."
