repo = "github.com/HiepPP/golang-practice-basic"
rule = "codelingo/go/default-in-type-switch"
sha = "afba2478c6adaa3c1f49071e93d0b9147122dfc5"

[[issues]]
  fileline = 9
  filepath = "Exercises/q19-MapFunctionWithInterfaces.go"
  fixed = false
  ignored = "incoming value returned in lieu of default"
