repo = "github.com/iawia002/annie"
rule = "codelingo/go/reassigned-error"
sha = "c24fbc04b8260cc5923af12be9baf30d35735325"

[[issues]]
  filepath = "extractors/tiktok/tiktok.go"
  fileline = 12
  comment = "Error was not checked before reassignment"
