repo = "github.com/uber-go/zap"
rule = "codelingo/go/unchecked-type-assertion"
sha = "ec2dc456c680236892af2c645172713e1c4e1acd"

[[issues]]
  filepath = "zapcore/error.go"
  fileline = 99
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "zapcore/write_syncer.go"
  fileline = 41
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "zapcore/error.go"
  fileline = 49
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "error.go"
  fileline = 63
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "buffer/pool.go"
  fileline = 41
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "zapcore/entry.go"
  fileline = 45
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "stacktrace.go"
  fileline = 49
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "field.go"
  fileline = 405
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "zapcore/console_encoder.go"
  fileline = 128
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."

[[issues]]
  filepath = "zapcore/encoder_test.go"
  fileline = 630
  comment = "Unchecked type assertions can cause panics. Check for success with the x, ok := y.(type) style."
