repo = "github.com/micro/go-micro"
rule = "codelingo/go/pointer-leaves-method"
sha = "03031a694da1b256d0d7f2afb1a2926954c63c85"

[[issues]]
  filepath = "config/source/memory/memory.go"
  fileline = 35
  comment = "The receiver pointer is returned from this method. Make a copy instead."

[[issues]]
  filepath = "registry/mdns_registry.go"
  fileline = 380
  comment = "The receiver pointer is returned from this method. Make a copy instead."
