repo = "github.com/cnlh/nps"
rule = "codelingo/go/default-in-type-switch"
sha = "c9b755360c3b3513e53bb265ae49703f06d6f34f"

[[issues]]
  filepath = "lib/conn/conn.go"
  fileline = 144
  comment = "Always include a default case when using a type switch."

[[issues]]
  filepath = "lib/conn/conn.go"
  fileline = 159
  comment = "Always include a default case when using a type switch."
