repo = "github.com/smnalex/twilio-go"
rule = "codelingo/go/shadowed-variable"
sha = "084bf9682c344da52a7fd908ccbba0beee9753f2"

[[issues]]
  filepath = "chat/chat_test.go"
  fileline = 37

[[issues]]
  filepath = "chat/httpclient_mock_test.go"
  fileline = 48

[[issues]]
  filepath = "chat/httpclient_mock_test.go"
  fileline = 128

[[issues]]
  filepath = "chat/httpclient_mock_test.go"
  fileline = 93
