repo = "github.com/mjs/directnic_ddns"
rule = "codelingo/go/shadowed-variable"
sha = "6082c54efb4389e02259894f5f83534438609803"

[[issues]]
  filepath = "vendor/github.com/pelletier/go-toml/lexer.go"
  fileline = 651

[[issues]]
  filepath = "vendor/github.com/pelletier/go-toml/lexer.go"
  fileline = 699
