repo = "github.com/quii/learn-go-with-tests"
rule = "codelingo/go/shadowed-variable"
sha = "d84a9bd65fceb46b318cda32920efd2232f3b2de"

[[issues]]
  filepath = "websockets/v2/vendor/github.com/gorilla/websocket/conn.go"
  fileline = 854
  comment = "Variable p shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "websockets/v1/vendor/github.com/gorilla/websocket/conn.go"
  fileline = 854
  comment = "Variable p shadows a variable of the same name declared in an outer scope."
