repo = "github.com/nsqio/nsq"
rule = "codelingo/go/shadowed-variable"
sha = "ec05c1ee206dffcdc03c84a88cfaf208b4c01fbb"

[[issues]]
  filepath = "internal/clusterinfo/data.go"
  fileline = 687
  comment = "Variable qs shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1901
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1801
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 197
  comment = "Variable msg shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "nsqd/protocol_v2_test.go"
  fileline = 1563
  comment = "Variable data shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "apps/nsq_to_nsq/nsq_to_nsq.go"
  fileline = 154
  comment = "Variable ok shadows a variable of the same name declared in an outer scope."

[[issues]]
  filepath = "nsqlookupd/lookup_protocol_v1.go"
  fileline = 130
  comment = "Variable key shadows a variable of the same name declared in an outer scope."
