repo = "github.com/caddyserver/caddy"
rule = "codelingo/go/insecure-http-connection"
sha = "891446d06340db2912c9a970bfe862bd54efbb70"

[[issues]]
  filepath = "caddyhttp/proxy/proxy_test.go"
  fileline = 523
  comment = "Skipping verification exposes the connection to man-in-the-middle attacks. This should only be used for testing."
